Repository woowacourse-teams/2024-coduo, pull requests merged in 2024-10, with the labels that each got.

#683 [BE] check api 호출 시 예외 수정
  backend/src/main/java/site/coduo/member/controller/AuthController.java
  backend/src/main/java/site/coduo/member/service/AuthService.java
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java
  backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
Labels: 🪨 etc

#688 [BE] 타이머 무한 스케줄링 에러 해결
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
  backend/src/main/java/site/coduo/sync/service/SchedulerService.java
  backend/src/main/java/site/coduo/timer/repository/TimerRepository.java
  backend/src/main/java/site/coduo/timer/service/TimerService.java
  backend/src/test/java/site/coduo/timer/repository/TimerRepositoryTest.java
Labels: 🌋 bug, ⚙️ refactor

#701 [FE] 🚀 로그인 콜백 버그 픽스
  frontend/src/App.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/pages/Callback/Callback.styles.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/Error/Error.styles.ts
  frontend/src/pages/Error/Error.tsx
  frontend/src/pages/Error/PageNotFound.styles.ts
  frontend/src/pages/Error/PageNotFound.tsx
Labels: 🌋 bug, 🏗️ infra, ⚙️ refactor

#707 [BE] SSE 타임아웃이 발생하면 멈추는 문제 해결
  backend/src/main/java/site/coduo/sync/service/SseEventStream.java
Labels: 🌋 bug

#714 [FE] 🚀 로그인 콜백 네비게이션 버그 픽스
  frontend/src/pages/Callback/Callback.tsx
Labels: 🌋 bug, ⚙️ refactor, 🚑 hotfix

#720 [FE] 🚀 버그 영역에 콘솔 출력 추가
  frontend/src/App.tsx
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/Main/Main.tsx
Labels: 🌋 bug, 🏗️ infra, ⚙️ refactor

#723 [FE] 🚀 로그인 콜백 버그 픽스
  frontend/src/App.tsx
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/Main/Main.tsx
Labels: 🌋 bug, 🏗️ infra, ⚙️ refactor

#722 [BE] 페어룸 존재 여부 확인 API
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomExistResponse.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
Labels: 🧑‍💻 feat

#593 [BE] 링크 삭제시 액세스코드 검증
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java
  backend/src/main/java/site/coduo/referencelink/repository/OpenGraphRepository.java
  backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkRepository.java
  backend/src/main/java/site/coduo/referencelink/service/OpenGraphService.java
  backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
  backend/src/test/java/site/coduo/referencelink/fake/FakeServer.java
  backend/src/test/java/site/coduo/referencelink/fake/FakeServerTest.java
  backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
Labels: 🧪 test

#735 refactor: 페어룸 존재 여부 확인 API 변경
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
Labels: ⚙️ refactor

#696 [FE] 오프라인 베타 테스트 대비 수정
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.styles.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/hooks/PairRoomOnboarding/usePairRoomMission.ts
  frontend/src/validations/validateBranchName.ts
Labels: ⚙️ refactor

#737 [FE] 페어룸 존재 여부 확인 API 연동 및 버그 픽스
  frontend/src/apis/pairRoom.ts
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/pages/SignUp/SignUp.styles.ts
  frontend/src/pages/SignUp/SignUp.tsx
Labels: 🌋 bug, 🧑‍💻 feat, ⚙️ refactor

#738 [FE] 🚀 테스트 서버 배포
  frontend/src/apis/pairRoom.ts
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.styles.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/Reference/Reference.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/hooks/PairRoomOnboarding/usePairRoomMission.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/pages/SignUp/SignUp.styles.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/validations/validateBranchName.ts
Labels: 🏗️ infra

#744 [FE] Header가 항상 화면 최상단에 보이도록 수정
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/common/useHashScroll.ts
  frontend/src/pages/Layout.styles.ts
  frontend/src/pages/Layout.tsx
Labels: ⚙️ refactor

#448 [BE] 스웨거 서버에서 https://coduo.site 추가
  backend/src/main/java/site/coduo/common/infrastructure/swagger/config/SwaggerConfig.java
Labels: 🌋 bug

#762 [FE] 페어룸 삭제 기능 구현
  frontend/src/apis/pairRoom.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.styles.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/MyPage/PairRoomDeleteModal/PairRoomDeleteModal.tsx
  frontend/src/components/MyPage/PairRoomDeleteModal/PariRoomDeleteModal.styles.ts
  frontend/src/constants/message.ts
  frontend/src/pages/Layout.styles.ts
  frontend/src/queries/MyPage/useDeleteRoom.ts
Labels: 🧑‍💻 feat

#765 [FE] 페어룸 추가 안내 모달 구현
  frontend/.stylelintrc
  frontend/src/components/PairRoom/GuideModal/GuideModal.styles.ts
  frontend/src/components/PairRoom/GuideModal/GuideModal.tsx
  frontend/src/components/common/Tooltip/Tooltip.styles.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
Labels: 🧑‍💻 feat, 💄 design

#769 [FE] 🚀 테스트 서버 배포
  frontend/.stylelintrc
  frontend/src/apis/pairRoom.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.styles.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/MyPage/PairRoomDeleteModal/PairRoomDeleteModal.tsx
  frontend/src/components/MyPage/PairRoomDeleteModal/PariRoomDeleteModal.styles.ts
  frontend/src/components/PairRoom/GuideModal/GuideModal.styles.ts
  frontend/src/components/PairRoom/GuideModal/GuideModal.tsx
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Tooltip/Tooltip.styles.ts
  frontend/src/constants/message.ts
  frontend/src/hooks/common/useHashScroll.ts
  frontend/src/pages/Layout.styles.ts
  frontend/src/pages/Layout.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/MyPage/useDeleteRoom.ts
Labels: 🏗️ infra, 🧑‍💻 feat, ⚙️ refactor

#787 [BE] 무중단 배포 스크립트 작성
  .github/workflows/be_cd-test.yml
  backend/src/main/resources/application-test.yml
Labels: 🏗️ infra

#788 [BE] 테스트 서버 주소 하드 코딩
  .github/workflows/be_cd-test.yml
Labels: 🏗️ infra

#789 [BE] 무중단 배포를 위해 도커 컴포즈 파일 수정
  backend/be_app-docker-compose.yml
Labels: 🏗️ infra

#791 chore: 블루 그린 무중단을 위한 도커 컴포즈 파일 변경
  backend/be_app-docker-compose.yml
Labels: 🏗️ infra

#793 [BE] curl 시 로컬 호스트로 변경
  .github/workflows/be_cd-test.yml
Labels: 🏗️ infra

#794 chore: 그린 서버 포트 바인딩 8081로 변경
  backend/be_app-docker-compose.yml
Labels: 🏗️ infra

#777 [FE] 페어룸 내에서도 미션 리포지토리를 확인할 수 있도록 추가
  frontend/src/apis/pairRoom.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/components/PairRoom/PairListCard/RepositorySection/RepositorySection.styles.ts
  frontend/src/components/PairRoom/PairListCard/RepositorySection/RepositorySection.tsx
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.tsx
  frontend/src/components/PairRoomOnboarding/MissionSettingSection/MissionSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/PairRoomSettingSection/PairRoomSettingSection.tsx
  frontend/src/hooks/PairRoomOnboarding/useMissionBranch.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/Main/useAddPairRoom.ts
  frontend/src/queries/PairRoom/useGetPairRoom.ts
  frontend/src/queries/PairRoomOnboarding/useCreateBranch.ts
Labels: 🧑‍💻 feat, ⚙️ refactor, 💄 design

#778 [FE] 회원 탈퇴 API 연동
  frontend/src/apis/member.ts
  frontend/src/components/MyPage/ConfirmModal/ConfirmModal.styles.ts
  frontend/src/components/MyPage/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/constants/message.ts
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/queries/MyPage/useDeleteMember.ts
  frontend/src/stores/userStore.ts
Labels: 🧑‍💻 feat, ⚙️ refactor

#798 🚀 테스트 서버 배포
  frontend/src/apis/member.ts
  frontend/src/apis/pairRoom.ts
  frontend/src/components/MyPage/ConfirmModal/ConfirmModal.styles.ts
  frontend/src/components/MyPage/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/components/PairRoom/PairListCard/RepositorySection/RepositorySection.styles.ts
  frontend/src/components/PairRoom/PairListCard/RepositorySection/RepositorySection.tsx
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.tsx
  frontend/src/components/PairRoomOnboarding/MissionSettingSection/MissionSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/PairRoomSettingSection/PairRoomSettingSection.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/constants/message.ts
  frontend/src/hooks/PairRoomOnboarding/useMissionBranch.ts
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/Main/useAddPairRoom.ts
  frontend/src/queries/MyPage/useDeleteMember.ts
  frontend/src/queries/PairRoom/useGetPairRoom.ts
  frontend/src/queries/PairRoomOnboarding/useCreateBranch.ts
  frontend/src/stores/userStore.ts
Labels: 🏗️ infra

#803 [BE] 페어룸 생성 요청 API 변경
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomCreateRequest.java
  backend/src/test/java/site/coduo/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/SseAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/TimerAcceptanceTest.java
  backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
  backend/src/test/java/site/coduo/timer/service/TimerServiceTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: ⚙️ refactor

#804 [BE] 테스트 서버 배포
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomCreateRequest.java
  backend/src/test/java/site/coduo/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/SseAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/TimerAcceptanceTest.java
  backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
  backend/src/test/java/site/coduo/timer/service/TimerServiceTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: 🏗️ infra, ⚙️ refactor

#805 [BE] 로컬 IP 주소 변경
  .github/workflows/be_cd-test.yml
Labels: 🏗️ infra

#820 [FE] 🚧 완료 상태 페어룸 1차 구현
  frontend/src/App.tsx
  frontend/src/apis/pairRoom.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/.DS_Store
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/.DS_Store
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/Header/Header.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/Reference/Reference.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/Reference/Reference.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/ReferenceList.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
  frontend/src/components/CompletedPairRoom/TodoListCard/Header/Header.styles.ts
  frontend/src/components/CompletedPairRoom/TodoListCard/Header/Header.tsx
  frontend/src/components/CompletedPairRoom/TodoListCard/TodoItem/TodoItem.styles.ts
  frontend/src/components/CompletedPairRoom/TodoListCard/TodoItem/TodoItem.tsx
  frontend/src/components/CompletedPairRoom/TodoListCard/TodoList/TodoList.styles.ts
  frontend/src/components/CompletedPairRoom/TodoListCard/TodoList/TodoList.tsx
  frontend/src/components/CompletedPairRoom/TodoListCard/TodoListCard.styles.ts
  frontend/src/components/CompletedPairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/components/MyPage/PairRoomDeleteModal/PariRoomDeleteModal.styles.ts
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.tsx
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/DeleteButton.stories.tsx
  frontend/src/components/PairRoom/PairListCard/DeleteButton/DeleteButton.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.stories.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/constants/message.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/pages/CompletedPairRoom/CompletedPairRoom.styles.ts
  frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/useCompletePairRoom.ts
Labels: 🧑‍💻 feat

#814 [FE] 페어룸 만들기, 페어룸 유형 선택하기 접근성 개선
  frontend/src/components/Landing/HowToPair/HowToPair.styles.ts
  frontend/src/components/Landing/HowToPair/HowToPair.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Modal/CloseButton/CloseButton.tsx
  frontend/src/components/common/Modal/Header/Header.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/ScrollIcon/ScrollIcon.tsx
  frontend/src/hooks/common/useAriaTrap.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Layout.tsx
  frontend/src/pages/Main/Main.tsx
Labels: 🪨 etc

#834 [FE] 페어룸 정보 입력하기 접근성 개선
  frontend/src/components/PairRoomOnboarding/CreateBranchInput/CreateBranchInput.tsx
  frontend/src/components/PairRoomOnboarding/InformationBox/InformationBox.tsx
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.tsx
  frontend/src/components/PairRoomOnboarding/MissionSettingSection/MissionSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
  frontend/src/components/PairRoomOnboarding/PairRoleInput/PairRoleInput.tsx
  frontend/src/components/PairRoomOnboarding/PairRoomSettingSection/PairRoomSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.tsx
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.tsx
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.tsx
  frontend/src/components/common/Dropdown/HiddenDropdown/HiddenDropdown.tsx
  frontend/src/components/common/HiddenMessage/HiddenMessage.styles.ts
  frontend/src/components/common/HiddenMessage/HiddenMessage.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
Labels: ⚙️ refactor

#837 [FE] 🚧 완료 상태 페어룸 2차 구현
  frontend/src/App.tsx
  frontend/src/apis/member.ts
  frontend/src/apis/retrospect.ts
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetroSpectButtonDisabled.tsx
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetrospectButton.styles.ts
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetrospectButton.tsx
  frontend/src/constants/message.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/CompletedPairRoom/CompletedPairRoom.styles.ts
  frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/CompletedPairRoom/useGetUserIsInPairRoom.ts
  frontend/src/queries/CompletedPairRoom/useGetUserRetrospectExists.ts
  frontend/src/queries/PairRoom/useGetPairRoom.ts
Labels: 🧑‍💻 feat

#828 [FE] 회고 페이지 구현
  frontend/src/App.tsx
  frontend/src/apis/retrospect.ts
  frontend/src/components/Retrospect/Question/Question.styles.ts
  frontend/src/components/Retrospect/Question/Question.tsx
  frontend/src/components/Retrospect/RetrospectForm/RetrospectForm.styles.ts
  frontend/src/components/Retrospect/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/Retrospect/RetrospectForm/SkipModal/SkipModal.tsx
  frontend/src/components/Retrospect/RetrospectHeader/Header/Header.styles.ts
  frontend/src/components/Retrospect/RetrospectHeader/Header/Header.tsx
  frontend/src/components/Retrospect/RetrospectHeader/RetrospectHeader.tsx
  frontend/src/components/Retrospect/RetrospectView/RetrospectView.styles.ts
  frontend/src/components/Retrospect/RetrospectView/RetrospectView.tsx
  frontend/src/constants/message.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/retrospect.ts
  frontend/src/hooks/Retrospect/useInputAnswer.ts
  frontend/src/hooks/common/usePreventPageRefresh.ts
  frontend/src/pages/Retrospect/Retrospect.styles.ts
  frontend/src/pages/Retrospect/Retrospect.tsx
  frontend/src/queries/Retrospect/useAddRetrospect.ts
  frontend/src/queries/Retrospect/useGetRetrospectAnswer.ts
Labels: 🧑‍💻 feat

#810 [BE] 페어룸에 깃허브 ID로 페어 추가 API
  backend/src/main/java/site/coduo/member/controller/MemberController.java
  backend/src/main/java/site/coduo/member/controller/docs/MemberControllerDocs.java
  backend/src/main/java/site/coduo/member/domain/Member.java
  backend/src/main/java/site/coduo/member/domain/MemberUpdate.java
  backend/src/main/java/site/coduo/member/domain/repository/MemberRepository.java
  backend/src/main/java/site/coduo/member/service/AuthService.java
  backend/src/main/java/site/coduo/member/service/MemberService.java
  backend/src/main/java/site/coduo/member/service/dto/member/MemberNameResponse.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomCreateRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomDeleteRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/TimerDurationCreateRequest.java
  backend/src/main/java/site/coduo/timer/service/dto/TimerCreateRequest.java
  backend/src/test/java/site/coduo/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/RetrospectAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/SseAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/TimerAcceptanceTest.java
  backend/src/test/java/site/coduo/fixture/PairRoomCreateRequestFixture.java
  backend/src/test/java/site/coduo/member/domain/repository/MemberRepositoryTest.java
  backend/src/test/java/site/coduo/member/service/MemberServiceTest.java
  backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
  backend/src/test/java/site/coduo/retrospect/service/RetrospectServiceTest.java
  backend/src/test/java/site/coduo/timer/service/TimerServiceTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: 🧑‍💻 feat

#842 [BE] 페어룸 생성시 github id 를 받아 페어 추가
  backend/src/main/java/site/coduo/member/controller/MemberController.java
  backend/src/main/java/site/coduo/member/controller/docs/MemberControllerDocs.java
  backend/src/main/java/site/coduo/member/domain/Member.java
  backend/src/main/java/site/coduo/member/domain/MemberUpdate.java
  backend/src/main/java/site/coduo/member/domain/repository/MemberRepository.java
  backend/src/main/java/site/coduo/member/service/AuthService.java
  backend/src/main/java/site/coduo/member/service/MemberService.java
  backend/src/main/java/site/coduo/member/service/dto/member/MemberNameResponse.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomCreateRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomDeleteRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/TimerDurationCreateRequest.java
  backend/src/main/java/site/coduo/timer/service/dto/TimerCreateRequest.java
  backend/src/test/java/site/coduo/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/RetrospectAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/SseAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/TimerAcceptanceTest.java
  backend/src/test/java/site/coduo/fixture/PairRoomCreateRequestFixture.java
  backend/src/test/java/site/coduo/member/domain/repository/MemberRepositoryTest.java
  backend/src/test/java/site/coduo/member/service/MemberServiceTest.java
  backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
  backend/src/test/java/site/coduo/retrospect/service/RetrospectServiceTest.java
  backend/src/test/java/site/coduo/timer/service/TimerServiceTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: 🧑‍💻 feat, ⚙️ refactor

#843 [FE] 사이드바 종료 버튼 구현 및 버그 수정
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetroSpectButtonDisabled.tsx
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/pages/CompletedPairRoom/CompletedPairRoom.styles.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
Labels: 🌋 bug, 💄 design

#845 [FE] 잘못된 api body id값 수정
  frontend/src/apis/retrospect.ts
  frontend/src/components/Retrospect/RetrospectForm/RetrospectForm.tsx
  frontend/src/hooks/Retrospect/useInputAnswer.ts
Labels: 🌋 bug

#848 [BE] 깃허브 id 로 조회
  backend/src/main/java/site/coduo/member/domain/repository/MemberRepository.java
  backend/src/main/java/site/coduo/member/service/MemberService.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/member/service/MemberServiceTest.java
Labels: 🏗️ infra

#849 [FE] 🚀 Member api 데이터 반환값 변경 핫픽스 테스트 배포
  frontend/src/apis/member.ts
  frontend/src/queries/CompletedPairRoom/useGetUserIsInPairRoom.ts
  frontend/src/queries/CompletedPairRoom/useGetUserRetrospectExists.ts
Labels: 🚑 hotfix

#850 [BE] 레퍼런스 링크 및 이미지 링크 그리고 오픈그래프 설명 길이 길이 제약 조건 변경
  backend/src/main/java/site/coduo/referencelink/domain/OpenGraph.java
  backend/src/main/java/site/coduo/referencelink/repository/OpenGraphEntity.java
  backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java
  backend/src/test/java/site/coduo/referencelink/domain/OpenGraphTest.java
Labels: 🌋 bug

#854 [FE] 깃허브 아이디를 통해 페어룸 공유 API 연동
  frontend/.eslintrc.cjs
  frontend/src/apis/member.ts
  frontend/src/apis/pairRoom.ts
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/PairRoomOnboarding/AddPairModal/AddPairModal.styles.ts
  frontend/src/components/PairRoomOnboarding/AddPairModal/AddPairModal.tsx
  frontend/src/components/PairRoomOnboarding/HowToPairModal/HowToPairModal.styles.ts
  frontend/src/components/PairRoomOnboarding/HowToPairModal/HowToPairModal.tsx
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.styles.ts
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
  frontend/src/components/PairRoomOnboarding/PairRoleInput/PairRoleInput.tsx
  frontend/src/components/PairRoomOnboarding/PairRoomSettingSection/PairRoomSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/PairRoom/useEditCategory.ts
  frontend/src/hooks/PairRoomOnboarding/useMissionBranch.ts
  frontend/src/hooks/PairRoomOnboarding/usePairRoomInformation.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/Main/useAddPairRoom.ts
  frontend/src/validations/validatePairName.ts
Labels: 🧑‍💻 feat, ⚙️ refactor

#862 [BE] 회고 사이즈 변경
  backend/src/main/java/site/coduo/retrospect/domain/RetrospectQuestionType.java
Labels: 🌋 bug

#875 [FE] 페어룸 온보딩 이름 입력 접근성 개선
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
Labels: ⚙️ refactor, 🪨 etc

#877 [BE] todo 정렬을 db에서 하지 않고 애플리케이션 단에서 변경
  backend/http/Reference-link.http
  backend/http/member.http
  backend/src/main/java/site/coduo/common/controller/CommonController.java
  backend/src/main/java/site/coduo/pairroom/domain/accesscode/generator/Adjective.java
  backend/src/main/java/site/coduo/pairroom/domain/accesscode/generator/EasyAccessCodeGenerator.java
  backend/src/main/java/site/coduo/pairroom/domain/accesscode/generator/UUIDAccessCodeGenerator.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/todo/domain/TodoSortComparator.java
  backend/src/main/java/site/coduo/todo/repository/TodoRepository.java
  backend/src/main/java/site/coduo/todo/service/TodoService.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: ⚙️ refactor

#882 [FE] RetrospectId 삭제 및 회고 페이지 라우터 수정
  frontend/src/App.tsx
  frontend/src/apis/retrospect.ts
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetrospectButton.tsx
  frontend/src/components/MyPage/PairRoomButton/RetrospectButton.tsx
  frontend/src/components/Retrospect/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/Retrospect/RetrospectView/RetrospectView.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/pages/MyPage/MyPageContent/MyPageContent.tsx
  frontend/src/pages/Retrospect/Retrospect.tsx
  frontend/src/queries/PairRoom/useCompletePairRoom.ts
  frontend/src/queries/Retrospect/useGetRetrospectAnswer.ts
Labels: 🌋 bug

#886 [FE] 페어룸 완료 페이지 리팩터링
  frontend/src/apis/retrospect.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetroSpectButtonDisabled.tsx
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetrospectButton.tsx
  frontend/src/components/CompletedPairRoom/TodoListCard/TodoListCard.styles.ts
  frontend/src/pages/CompletedPairRoom/CompletedPairRoom.styles.ts
  frontend/src/pages/CompletedPairRoom/CompletedPairRoom.tsx
  frontend/src/queries/CompletedPairRoom/useGetUserIsInPairRoom.ts
  frontend/src/queries/CompletedPairRoom/useGetUserRetrospectExists.ts
Labels: 🌋 bug, ⚙️ refactor

#881 [FE] 컴포넌트 리팩터링 (Input, Button, ReferenceCard)
  frontend/src/apis/referenceLink.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/Reference/Reference.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/Reference/Reference.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/ReferenceList.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/MyPage/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/PairRoom/GuideModal/GuideModal.tsx
  frontend/src/components/PairRoom/PairListCard/Header/Header.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoriesEditor.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoriesEditor.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/IconButton/IconButton.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/IconButton/IconButton.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/IconButton/IconButton.tsx
  frontend/src/components/PairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/Reference/Reference.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/Reference/Reference.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.styles.ts
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.tsx
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.styles.ts
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.tsx
  frontend/src/components/Retrospect/RetrospectForm/RetrospectForm.tsx
  frontend/src/components/Retrospect/RetrospectHeader/Header/Header.tsx
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Toast/Toast.styles.ts
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/hooks/PairRoom/useEditCategory.ts
  frontend/src/pages/Error/Error.tsx
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/PairRoom/category/mutation.ts
  frontend/src/queries/PairRoom/reference/mutation.ts
  frontend/src/validations/validateCategory.ts
Labels: ⚙️ refactor

#888 [FE] 회고 상태 유지되는 버그 수정
  frontend/src/hooks/Retrospect/useInputAnswer.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/useCompletePairRoom.ts
  frontend/src/queries/PairRoom/useGetPairRoom.ts
Labels: 🌋 bug

#896 [BE] 회고 예외 리팩터링
  backend/src/main/java/site/coduo/retrospect/domain/RetrospectContents.java
  backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
  backend/src/test/java/site/coduo/retrospect/domain/RetrospectContentsTest.java
  backend/src/test/java/site/coduo/retrospect/service/RetrospectServiceTest.java
Labels: 🌋 bug

#898 [FE] 페어룸 종료하기 확인 모달 구현
  frontend/src/components/MyPage/DeleteModal/DeleteModal.styles.ts
  frontend/src/components/MyPage/DeleteModal/DeleteModal.tsx
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/MyPage/PairRoomButton/RetrospectButton.tsx
  frontend/src/components/PairRoom/PairListCard/AccessCodeSection/AccessCodeSection.stories.tsx
  frontend/src/components/PairRoom/PairListCard/AccessCodeSection/AccessCodeSection.styles.ts
  frontend/src/components/PairRoom/PairListCard/AccessCodeSection/AccessCodeSection.tsx
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.tsx
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/DeleteButton.stories.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.stories.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.stories.tsx
  frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.tsx
  frontend/src/components/common/ConfirmModal/ConfirmModal.styles.ts
  frontend/src/components/common/ConfirmModal/ConfirmModal.tsx
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/useCompletePairRoom.ts
Labels: 🧑‍💻 feat

#900 [BE] 회고 전체 조회 시 작성 하지 않은 회고는 가져오지 않도록 변경
  backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
Labels: 🌋 bug

#902 [FE] 🚀 페어룸 정보 쿼리 무효화 추가
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/useGetPairRoom.ts
Labels: 🏗️ infra, 🚑 hotfix

#903 [FE] 🚀 잘못된 회고 페이지 경로 수정
  frontend/src/components/MyPage/PairRoomButton/RetrospectButton.tsx
  frontend/src/pages/MyPage/MyPageContent/ListLayout/ListLayout.tsx
  frontend/src/queries/Retrospect/useDeleteRetrospect.ts
Labels: 🏗️ infra, 🚑 hotfix

#908 [BE] 회고를 두번 이상 작성할 시 예외 던지도록 변경
  backend/src/main/java/site/coduo/retrospect/controller/error/RetrospectApiError.java
  backend/src/main/java/site/coduo/retrospect/exception/MaxRetrospectLimitException.java
  backend/src/main/java/site/coduo/retrospect/repository/RetrospectRepository.java
  backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
  backend/src/test/java/site/coduo/retrospect/service/RetrospectServiceTest.java
Labels: 🌋 bug

#907 [BE] 페어 연동할 때 자신의 깃허브 id로 연동시 예외 반환
  backend/src/main/java/site/coduo/member/controller/MemberController.java
  backend/src/main/java/site/coduo/member/controller/MemberExceptionHandler.java
  backend/src/main/java/site/coduo/member/controller/docs/MemberControllerDocs.java
  backend/src/main/java/site/coduo/member/controller/error/MemberApiError.java
  backend/src/main/java/site/coduo/member/domain/repository/MemberRepository.java
  backend/src/main/java/site/coduo/member/exception/InvalidMemberAddException.java
  backend/src/main/java/site/coduo/member/service/MemberService.java
Labels: 🌋 bug

#916 [FE] 카테고리 UI 수정
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.styles.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/MyPage/PairRoomButton/RetrospectButton.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Input/Input.tsx
Labels: 🧑‍💻 feat, ⚙️ refactor

#920 [FE] 완료된 페어룸 페이지 들어갈때 버튼에 로딩 스피너 추가
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetrospectButton.tsx
  frontend/src/components/common/Spinner/Spinner.styles.ts
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/queries/CompletedPairRoom/useGetUserIsInPairRoom.ts
  frontend/src/queries/CompletedPairRoom/useGetUserRetrospectExists.ts
Labels: 💄 design

#921 [FE] 🚀 테스트 서버 배포
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/CompletedPairRoom/RetrospectButton/RetrospectButton.tsx
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.styles.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/MyPage/PairRoomButton/RetrospectButton.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/common/Spinner/Spinner.styles.ts
Labels: 🌋 bug, 🏗️ infra, 🚑 hotfix

#924 [FE] 🚀 라우팅 버그 픽스
  frontend/src/App.tsx
Labels: 🏗️ infra

#938 [BE] 회고 중복 생성 버그 수정
  backend/src/main/java/site/coduo/retrospect/controller/RetrospectController.java
  backend/src/main/java/site/coduo/retrospect/controller/RetrospectExceptionHandler.java
  backend/src/main/java/site/coduo/retrospect/controller/error/RetrospectApiError.java
  backend/src/main/java/site/coduo/retrospect/exception/DuplicateRetrospectException.java
  backend/src/main/java/site/coduo/retrospect/exception/MaxRetrospectLimitException.java
  backend/src/main/java/site/coduo/retrospect/service/RetrospectService.java
  backend/src/test/java/site/coduo/retrospect/service/RetrospectServiceTest.java
Labels: 🌋 bug

#941 [FE] Dropdown 리팩터링
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/PairRoom/ReferenceCard/Footer/Footer.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/Footer/Footer.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoomOnboarding/PairRoleInput/PairRoleInput.tsx
  frontend/src/components/_common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/_common/Dropdown/Dropdown.styles.tsx
  frontend/src/components/_common/Dropdown/Dropdown.tsx
  frontend/src/components/_common/Dropdown/Dropdown/Dropdown.stories.tsx
  frontend/src/components/_common/Dropdown/Dropdown/Dropdown.styles.tsx
  frontend/src/components/_common/Dropdown/Dropdown/Dropdown.tsx
  frontend/src/components/_common/Dropdown/HiddenDropdown/HiddenDropdown.tsx
  frontend/src/components/_common/Dropdown/Label/Label.stories.tsx
  frontend/src/components/_common/Dropdown/Label/Label.styles.ts
  frontend/src/components/_common/Dropdown/Label/Label.tsx
  frontend/src/components/_common/Dropdown/index.ts
  frontend/src/hooks/PairRoom/useReference.ts
  frontend/src/utils/findOption.ts
Labels: ⚙️ refactor

#940 [FE] Button 리팩터링
  frontend/src/components/CompletedPairRoom/ReferenceCard/Header/Header.styles.ts
  frontend/src/components/CompletedPairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.styles.ts
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/GuideModal/GuideModal.styles.ts
  frontend/src/components/PairRoom/GuideModal/GuideModal.tsx
  frontend/src/components/PairRoom/PairListCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/PairListCard/Header/Header.tsx
  frontend/src/components/PairRoom/ReferenceCard/Footer/Footer.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/Footer/Footer.tsx
  frontend/src/components/PairRoom/ReferenceCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.styles.ts
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/components/PairRoomOnboarding/MissionSettingSection/MissionSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.styles.ts
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.styles.ts
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.tsx
  frontend/src/components/Retrospect/Header/Header.styles.ts
  frontend/src/components/Retrospect/Header/Header.tsx
  frontend/src/components/_common/Button/Button.stories.tsx
  frontend/src/components/_common/Button/Button.styles.ts
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/Button/Button.type.ts
  frontend/src/components/_common/ConfirmModal/ConfirmModal.tsx
  frontend/src/pages/Error/Error.styles.ts
  frontend/src/pages/Error/Error.tsx
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/RetrospectForm/RetrospectForm.styles.ts
  frontend/src/pages/RetrospectForm/RetrospectForm.tsx
  frontend/src/pages/SignUp/SignUp.styles.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/utils/calculateButtonColor.ts
Labels: ⚙️ refactor
