Repository woowacourse-teams/2024-coduo, pull requests merged in 2024-12, with the labels that each got.

#976 [FE] 테스트 배포 환경에서 아이콘 버튼이 이상하게 보이는 오류 수정
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/_common/IconButton/IconButton.styles.ts
Labels: 🌋 bug, 💄 design

#975 [FE] 테스트 서버 색상 수정
  frontend/src/components/PairRoom/GuideModal/GuideModal.stories.tsx
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.stories.tsx
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.styles.ts
  frontend/src/components/Retrospect/Textarea/Textarea.stories.tsx
  frontend/src/pages/CompletedPairRoom/CompletedPairRoom.styles.ts
Labels: 💄 design

#984 [FE] 색상 및 버튼 디자인 오류 해결
  frontend/src/components/CompletedPairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/CompletedPairRoom/ReferenceCard/ReferenceList/ReferenceList.styles.ts
  frontend/src/components/CompletedPairRoom/TodoListCard/TodoItem/TodoItem.styles.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/pages/SignUp/SignUp.tsx
Labels: 🌋 bug, 💄 design

#990 [FE] 페이지 뒤로가기 오류 해결
  frontend/src/pages/PrivateRoutes.tsx
Labels: 🌋 bug

#987 [FE] 버그 해결
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/GuideModal/GuideModal.tsx
  frontend/src/components/PairRoomOnboarding/AddPairModal/AddPairModal.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/ConfirmModal/ConfirmModal.tsx
  frontend/src/hooks/_common/customEvent/useClickEnterKey.ts
  frontend/src/pages/RetrospectForm/RetrospectForm.styles.ts
Labels: 🌋 bug, ⚙️ refactor

#993 [FE] 코딩해듀오 docs 페이지 리팩터링 및 이미지 배포
  frontend/src/components/CoduoDocs/ContentBox/ContentBox.styles.ts
  frontend/src/components/CoduoDocs/DocsImage/DocsImage.stories.tsx
  frontend/src/components/CoduoDocs/DocsImage/DocsImage.tsx
  frontend/src/components/CoduoDocs/FloatingSidebar/FloatingSidebar.stories.tsx
  frontend/src/components/CoduoDocs/FloatingSidebar/FloatingSidebar.styles.ts
  frontend/src/components/CoduoDocs/Quote/Quote.tsx
  frontend/src/components/CoduoDocs/SourceCode/SourceCode.styles.ts
  frontend/src/components/CoduoDocs/Steps/Steps.styles.ts
  frontend/src/components/CoduoDocs/Steps/Steps.tsx
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/constants/coduoDocs.ts
  frontend/src/constants/coduoDocs/howToStart.ts
  frontend/src/constants/coduoDocs/index.ts
  frontend/src/constants/coduoDocs/pairProgrammingConcept.ts
  frontend/src/constants/coduoDocs/sidebar.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.styles.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.tsx
Labels: ✏️ docs, ⚙️ refactor, 🪨 etc
