Repository woowacourse-teams/2024-coduo, pull requests merged in 2024-07, with the labels that each got.

#11 [FE] 프로젝트 생성 및 개발 환경 설정
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.prettierrc
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/logo.png
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🏗️ infra, 🧑‍💻 feat, ☕️ meeting, 🚔 policy

#39 [BE] ReferenceLink 검증 추가
  backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
  backend/src/main/java/site/coduo/referencelink/exception/InvalidUrlFormatException.java
  backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkEntity.java
  backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkRepository.java
  backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
  backend/src/test/java/site/coduo/referencelink/domain/ReferenceLinkEntityTest.java
  backend/src/test/java/site/coduo/referencelink/domain/ReferenceLinkTest.java
  backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
Labels: ⚙️ refactor

#48 [FE] 공통 컴포넌트(모달) 구현
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/package.json
  frontend/src/components/common/Modal/Body/Body.stories.ts
  frontend/src/components/common/Modal/Body/Body.styles.ts
  frontend/src/components/common/Modal/Body/Body.tsx
  frontend/src/components/common/Modal/CloseButton/CloseButton.stories.ts
  frontend/src/components/common/Modal/CloseButton/CloseButton.styles.ts
  frontend/src/components/common/Modal/CloseButton/CloseButton.tsx
  frontend/src/components/common/Modal/Footer/Footer.stories.tsx
  frontend/src/components/common/Modal/Footer/Footer.styles.ts
  frontend/src/components/common/Modal/Footer/Footer.tsx
  frontend/src/components/common/Modal/Header/Header.stories.tsx
  frontend/src/components/common/Modal/Header/Header.styles.ts
  frontend/src/components/common/Modal/Header/Header.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.styles.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/Modal.type.ts
  frontend/src/components/common/Modal/index.ts
  frontend/src/hooks/useEscapeKey.ts
  frontend/src/hooks/useFocusTrap.ts
  frontend/src/hooks/usePreventScroll.ts
  frontend/yarn.lock
Labels: 🧑‍💻 feat

#46 [FE] 공통 컴포넌트(헤더) 구현
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package.json
  frontend/src/assets/images/logo_icon.svg
  frontend/src/assets/images/logo_icon_with_title.svg
  frontend/src/assets/images/logo_title.svg
  frontend/src/assets/index.ts
  frontend/src/assets/logo.png
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/Header.style.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/types.d.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🧑‍💻 feat

#47 [FE] 공통 컴포넌트(버튼) 구현
  frontend/src/components/common/Button/Button.stories.tsx
  frontend/src/components/common/Button/Button.styles.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Button/Button.type.tsx
  frontend/src/styles/theme.ts
Labels: 🧑‍💻 feat

#51 [FE] 페이지 라우팅 설정
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/Main.tsx
  frontend/yarn.lock
Labels: 🧑‍💻 feat

#52 [FE] 공통 컴포넌트(Input) 구현
  frontend/.storybook/preview.tsx
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Input/Input.type.ts
Labels: 🧑‍💻 feat

#56 [FE] 공통 Dropdown 구현
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.stories.tsx
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.tsx
  frontend/src/components/common/Dropdown/HiddenDropdown/HiddenDropdown.tsx
Labels: 🧑‍💻 feat

#66 [FE] 메인 페이지 UI 구현
  frontend/src/App.tsx
  frontend/src/assets/images/wave.svg
  frontend/src/assets/index.ts
  frontend/src/pages/Layout.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/Main/Main.styles.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/styles/theme.ts
Labels: 🧑‍💻 feat

#78 [FE] 모달 높이 옵션 추가
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.styles.ts
  frontend/src/components/common/Modal/Modal.tsx
Labels: ⚙️ refactor

#84 [FE] Button disabled border 수정
  frontend/src/components/common/Button/Button.styles.ts
Labels: 🌋 bug

#87 [FE] Input width, height 프롭스 수정
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Input/Input.tsx
Labels: 🚑 hotfix

#89 [BE] pairRoomController 테스트를 PairRoomAcceptance 테스트로 변경
  backend/src/test/java/site/coduo/acceptance/AcceptanceFixture.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
Labels: 🧪 test, ⚙️ refactor

#94 [BE] 페어룸 삭제 API 구현
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/main/java/site/coduo/pairroom/dto/PairRoomDeleteRequest.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
Labels: 🧑‍💻 feat

#85 [FE] 페어룸 생성 모달 구현
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/fetcher.ts
  frontend/src/apis/pairName.ts
  frontend/src/components/CreatePairRoomModal/CompleteCreatePairRoom.stories.tsx
  frontend/src/components/CreatePairRoomModal/CompleteCreatePairRoom.tsx
  frontend/src/components/CreatePairRoomModal/CreatePairRoom.tsx
  frontend/src/components/CreatePairRoomModal/CreatePairRoomModal.stories.tsx
  frontend/src/components/CreatePairRoomModal/CreatePairRoomModal.styles.ts
  frontend/src/components/CreatePairRoomModal/CreatePairRoomModal.tsx
  frontend/src/constants/pairRoomModalInfo.ts
  frontend/src/hooks/pairRoomModal/usePairNameInputs.ts
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useModal.ts
  frontend/src/pages/Main/Main.tsx
  frontend/yarn.lock
Labels: 🧑‍💻 feat

#113 [BE] 컨트롤러 메서드 명 수정 및 dto 검증 추가
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/dto/PairRoomCreateRequest.java
  backend/src/main/java/site/coduo/pairroom/dto/PairRoomDeleteRequest.java
  backend/src/main/java/site/coduo/pairroom/dto/PairRoomReadRequest.java
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java
  backend/src/main/java/site/coduo/referencelink/controller/docs/ReferenceLinkDocs.java
Labels: ⚙️ refactor

#116 [FE] 페어룸 역할 교환 기능 구현
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.stories.tsx
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/styles/theme.ts
Labels: 🧑‍💻 feat

#114 [FE] 페어룸 타이머 기능 구현
  frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/pages/PairRoom/PairRoom.styles.tsx
Labels: 🧑‍💻 feat

#106 [FE] 페어룸 온보딩 모달 UI 구현
  frontend/src/components/PairRoom/PairRoomOnboardingModal/FooterButtons/FooterButtons.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/PairRoomOnboardingModal.stories.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/PairRoomOnboardingModal.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/PairRoomOnboardingModal.type.ts
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Progress/Progress.stories.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Progress/ProgressBar.styles.ts
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Progress/ProgressBar.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Steps/RoleSetting.stories.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Steps/RoleSetting.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Steps/Steps.styles.ts
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Steps/TimerSetting.stories.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Steps/TimerSetting.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/constants.ts
Labels: 🧑‍💻 feat

#120 [FE] 레퍼런스 링크 저장 및 추가 구현
  frontend/src/apis/reference.ts
  frontend/src/components/PairRoom/ReferenceCard/Reference.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useModal.ts
Labels: 🧑‍💻 feat

#117 [FE] 페어 목록 리스트 구현
  frontend/src/components/PairRoom/PairListCard/DeleteButton/DeleteButton.stories.tsx
  frontend/src/components/PairRoom/PairListCard/DeleteButton/DeleteButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/DeleteButton/DeleteButton.tsx
  frontend/src/components/PairRoom/PairListCard/Header/Header.stories.tsx
  frontend/src/components/PairRoom/PairListCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/PairListCard/Header/Header.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.stories.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.stories.tsx
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.tsx
  frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.stories.tsx
  frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.styles.ts
  frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
Labels: 🧑‍💻 feat

#137 [FE] 👽 env 파일 생성을 위한 config 파일 설정
  frontend/package.json
  frontend/src/apis/constants.ts
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🏗️ infra

#143 [BE] 레퍼런스 링크 API 수정
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java
  backend/src/main/java/site/coduo/referencelink/controller/docs/ReferenceLinkDocs.java
Labels: 🧑‍💻 feat

#152 [FE] 유닛 테스트와 스토리북 배포 분리
  .github/workflows/fe-ci.yml
Labels: 🏗️ infra

#151 [FE] 페어룸 온보딩 페이지 기능 구현
  frontend/src/App.tsx
  frontend/src/apis/pairName.ts
  frontend/src/apis/reference.ts
  frontend/src/apis/referenceLink.ts
  frontend/src/components/CreatePairRoomModal/CompleteCreatePairRoom.stories.tsx
  frontend/src/components/CreatePairRoomModal/CompleteCreatePairRoom.tsx
  frontend/src/components/CreatePairRoomModal/CreatePairRoomModal.tsx
  frontend/src/components/PairRoom/OnboardingModal/FooterButtons/FooterButtons.tsx
  frontend/src/components/PairRoom/OnboardingModal/OnboardingModal.stories.tsx
  frontend/src/components/PairRoom/OnboardingModal/OnboardingModal.tsx
  frontend/src/components/PairRoom/OnboardingModal/OnboardingModal.type.ts
  frontend/src/components/PairRoom/OnboardingModal/ProgressBar/ProgressBar.stories.tsx
  frontend/src/components/PairRoom/OnboardingModal/ProgressBar/ProgressBar.styles.ts
  frontend/src/components/PairRoom/OnboardingModal/ProgressBar/ProgressBar.tsx
  frontend/src/components/PairRoom/OnboardingModal/Steps/RoleSetting.stories.tsx
  frontend/src/components/PairRoom/OnboardingModal/Steps/RoleSetting.tsx
  frontend/src/components/PairRoom/OnboardingModal/Steps/Steps.styles.ts
  frontend/src/components/PairRoom/OnboardingModal/Steps/TimerSetting.stories.tsx
  frontend/src/components/PairRoom/OnboardingModal/Steps/TimerSetting.tsx
  frontend/src/components/PairRoom/OnboardingModal/constants.ts
  frontend/src/components/PairRoom/PairListCard/DeleteButton/DeleteButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/Header/Header.tsx
  frontend/src/components/PairRoom/PairListCard/PairListCard.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.tsx
  frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.styles.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/PairRoomOnboardingModal.stories.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/PairRoomOnboardingModal.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Steps/RoleSetting.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/Steps/TimerSetting.tsx
  frontend/src/components/PairRoom/PairRoomOnboardingModal/constants.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/constants/api.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/useModal.ts
  frontend/src/pages/PairRoom/PairRoom.styles.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/webpack.config.js
Labels: 🧑‍💻 feat, ⚙️ refactor

#125 [FE] 방 참가하기 모달 구현
  frontend/src/apis/reference.ts
  frontend/src/apis/roomCode.ts
  frontend/src/components/CreatePairRoomModal/CreatePairRoomModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/pages/Main/Main.tsx
Labels: 🧑‍💻 feat

#174 [FE] CI 로직 수정
  .github/workflows/fe-ci.yml
Labels: ✏️ docs

#181 [FE] 글로벌 폰트 때문에 화면이 흔들리는 버그 개선
  frontend/public/fonts/Pretendard-Regular.ttf
  frontend/src/assets/fonts/Pretendard-Bold.woff2
  frontend/src/assets/fonts/Pretendard-Light.woff2
  frontend/src/assets/fonts/Pretendard-Medium.woff2
  frontend/src/assets/fonts/Pretendard-Regular.woff2
  frontend/src/assets/fonts/Pretendard-SemiBold.woff2
  frontend/src/index.tsx
  frontend/src/styles/Global.style.tsx
  frontend/src/styles/font.css
  frontend/webpack.config.js
Labels: 🌋 bug

#175 [FE] 페어룸 온보딩 페이지 버그 개선
  frontend/src/components/PairRoom/OnboardingModal/FooterButtons/FooterButtons.tsx
  frontend/src/components/PairRoom/OnboardingModal/OnboardingModal.styles.ts
  frontend/src/components/PairRoom/OnboardingModal/OnboardingModal.tsx
  frontend/src/components/PairRoom/OnboardingModal/Steps/RoleSetting.tsx
  frontend/src/components/PairRoom/OnboardingModal/Steps/Steps.styles.ts
  frontend/src/components/PairRoom/OnboardingModal/Steps/TimerSetting.stories.tsx
  frontend/src/components/PairRoom/OnboardingModal/Steps/TimerSetting.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/utils/validate.ts
Labels: 🌋 bug

#187 [FE] styled-component linting 적용
  frontend/.stylelintrc
  frontend/package.json
  frontend/yarn.lock
Labels: 🚔 policy

#192 [FE] 컨벤션에 맞게 css 스타일 재정렬 및 표현 수정
  frontend/.stylelintrc
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.styles.ts
  frontend/src/components/PairRoom/PairListCard/DeleteButton/DeleteButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.styles.ts
  frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.styles.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/components/PairRoom/PairRoomCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts
  frontend/src/components/PairRoomOnBoarding/InformationBox/InformationBox.styles.ts
  frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.styles.ts
  frontend/src/components/PairRoomOnBoarding/RoleSettingSection/RoleSettingSection.styles.ts
  frontend/src/components/PairRoomOnBoarding/TimerSettingSection/TimerSettingSection.styles.ts
  frontend/src/components/common/Button/Button.styles.ts
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Modal/Body/Body.styles.ts
  frontend/src/components/common/Modal/CloseButton/CloseButton.styles.ts
  frontend/src/components/common/Modal/Footer/Footer.styles.ts
  frontend/src/components/common/Modal/Header/Header.styles.ts
  frontend/src/components/common/Modal/Modal.styles.ts
  frontend/src/pages/Main/Main.styles.ts
  frontend/src/pages/PairRoom/PairRoom.styles.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
Labels: ⚙️ refactor

#193 [FE] storybook wrapping 분리하기
  frontend/.storybook/preview.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.stories.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.stories.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.stories.tsx
Labels: ⚙️ refactor

#194 [FE] 상수화 리팩토링
  frontend/src/apis/constants.ts
  frontend/src/apis/pairName.ts
  frontend/src/apis/reference.ts
  frontend/src/apis/referenceLink.ts
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreate/PairRoomCreate.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.stories.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoomOnBoarding/FooterButtons/FooterButtons.tsx
  frontend/src/constants/button.ts
  frontend/src/constants/message.ts
  frontend/src/constants/pairRoomModalInfo.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
Labels: ⚙️ refactor

#195 [FE] type 리팩터링
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoomOnBoarding/FooterButtons/FooterButtons.tsx
  frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.stories.tsx
  frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.tsx
  frontend/src/components/PairRoomOnBoarding/RoleSettingSection/RoleSettingSection.tsx
  frontend/src/components/common/Button/Button.styles.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Button/Button.type.ts
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/Input/Input.type.ts
  frontend/src/components/common/Modal/Footer/Footer.styles.ts
  frontend/src/components/common/Modal/Footer/Footer.tsx
  frontend/src/components/common/Modal/Modal.styles.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/Modal.type.ts
  frontend/src/constants/pairRoomModalInfo.ts
  frontend/src/hooks/Main/usePairNameInputs.test.tsx
  frontend/src/hooks/Main/usePairNameInputs.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.type.ts
Labels: ⚙️ refactor

#201 [FE]타입 충돌 해결
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoomOnBoarding/TimerSettingSection/TimerSettingSection.tsx
  frontend/src/components/common/Modal/Modal.stories.tsx
Labels: 🌋 bug
