Repository woowacourse-teams/2024-coduo, pull requests merged in 2024-11, with the labels that each got.

#949 [BE] 페어룸 종료 기능 추가
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomExceptionHandler.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/main/java/site/coduo/pairroom/controller/error/PairRoomApiError.java
  backend/src/main/java/site/coduo/pairroom/exception/DeletePairRoomException.java
  backend/src/main/java/site/coduo/pairroom/exception/InactivePairRoomException.java
  backend/src/main/java/site/coduo/pairroom/repository/PairRoomEntity.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/referencelink/service/CategoryService.java
  backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
  backend/src/main/java/site/coduo/todo/service/TodoService.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/RetrospectAcceptanceTest.java
  backend/src/test/java/site/coduo/pairroom/domain/PairRoomEntityTest.java
  backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: 🧑‍💻 feat

#946 [FE] Input 컴포넌트 리팩터링
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/Footer/Footer.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/Footer/Footer.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/components/PairRoomOnboarding/AddPairModal/AddPairModal.styles.ts
  frontend/src/components/PairRoomOnboarding/AddPairModal/AddPairModal.tsx
  frontend/src/components/PairRoomOnboarding/CreateBranchInput/CreateBranchInput.tsx
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.styles.ts
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.styles.ts
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.tsx
  frontend/src/components/_common/Input/Input.stories.tsx
  frontend/src/components/_common/Input/Input.styles.ts
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/components/_common/InputField/Content/Content.stories.ts
  frontend/src/components/_common/InputField/Content/Content.styles.ts
  frontend/src/components/_common/InputField/Content/Content.tsx
  frontend/src/components/_common/InputField/Input.type.ts
  frontend/src/components/_common/InputField/Input/Input.stories.tsx
  frontend/src/components/_common/InputField/Input/Input.styles.ts
  frontend/src/components/_common/InputField/Input/Input.tsx
  frontend/src/components/_common/InputField/InputField.stories.tsx
  frontend/src/components/_common/InputField/Label/Label.stories.ts
  frontend/src/components/_common/InputField/Label/Label.styles.ts
  frontend/src/components/_common/InputField/Label/Label.tsx
  frontend/src/components/_common/InputField/Layout/Layout.styles.ts
  frontend/src/components/_common/InputField/Layout/Layout.tsx
  frontend/src/components/_common/InputField/Message/Message.stories.ts
  frontend/src/components/_common/InputField/Message/Message.styles.ts
  frontend/src/components/_common/InputField/Message/Message.tsx
  frontend/src/components/_common/InputField/index.ts
  frontend/src/hooks/PairRoomOnboarding/usePairRoomInformation.ts
  frontend/src/hooks/_common/useInput.test.ts
  frontend/src/hooks/_common/useInput.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/validations/validateBranchName.ts
  frontend/src/validations/validateCategory.ts
  frontend/src/validations/validatePairName.ts
Labels: ⚙️ refactor

#957 [FE] IconButton 구현
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/CategoryManagementModal/IconButton/IconButton.styles.ts
  frontend/src/components/PairRoom/CategoryManagementModal/IconButton/IconButton.tsx
  frontend/src/components/PairRoom/PairListCard/CompleteRoomButton/CompleteRoomButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/PairListCard/Header/Header.tsx
  frontend/src/components/PairRoom/PairRoomCard/Header/Header.tsx
  frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.styles.ts
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/_common/IconButton/IconButton.stories.tsx
  frontend/src/components/_common/IconButton/IconButton.styles.ts
  frontend/src/components/_common/IconButton/IconButton.tsx
  frontend/src/components/_common/Modal/CloseButton/CloseButton.styles.ts
  frontend/src/components/_common/Modal/CloseButton/CloseButton.tsx
  frontend/src/styles/theme.ts
  frontend/src/utils/calculateButtonColor.ts
Labels: 🧑‍💻 feat

#963 [FE] TextButton 공통 컴포넌트 구현
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.styles.ts
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
  frontend/src/components/_common/Header/Header.styles.ts
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/components/_common/IconButton/IconButton.tsx
  frontend/src/components/_common/TextButton/TextButton.stories.tsx
  frontend/src/components/_common/TextButton/TextButton.styles.ts
  frontend/src/components/_common/TextButton/TextButton.tsx
  frontend/src/components/_common/TextButton/TextButton.type.ts
Labels: 🧑‍💻 feat

#970 [FE] 🚀 Netlify 배포 테스트
  frontend/src/index.tsx
  frontend/webpack.production.config.js
Labels: 🏗️ infra, 🚑 hotfix

#971 [FE] 🚀 Netlify Page Not Found 오류 해결
  frontend/netlify.toml
Labels: 🌋 bug, 🏗️ infra, 🚑 hotfix
