Repository woowacourse-teams/2024-coduo, pull requests merged in 2024-09, with the labels that each got.

#482 [BE] 필터에서 발생하는 예외 핸들링
  backend/src/main/java/site/coduo/common/config/FilterConfig.java
  backend/src/main/java/site/coduo/common/config/filter/AuthFailHandlerFilter.java
  backend/src/main/java/site/coduo/common/controller/CommonExceptionHandler.java
  backend/src/main/java/site/coduo/member/controller/MemberErrorController.java
  backend/src/main/java/site/coduo/member/controller/MemberExceptionHandler.java
  backend/src/main/java/site/coduo/member/controller/error/MemberApiError.java
  backend/src/main/java/site/coduo/member/exception/AuthorizationException.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomExceptionHandler.java
  backend/src/main/java/site/coduo/pairroomhistory/controller/PairRoomHistoryExceptionHandler.java
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkExceptionHandler.java
  backend/src/main/java/site/coduo/todo/controller/TodoExceptionHandler.java
  backend/src/test/java/site/coduo/acceptance/AuthAcceptanceTest.java
Labels: 🌋 bug

#510 [FE] 화면 크기에 따라 애니메이션이 끊겨 보이던 문제 해결
  frontend/src/pages/Landing/Landing.styles.ts
Labels: 🌋 bug

#516 [FE] 사이드바 리팩터링
  frontend/src/components/PairRoom/PairListCard/PairListCard.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
Labels: ⚙️ refactor

#505 [FE] 페어룸 타이머 및 온보딩 페이지 피드백 반영
  frontend/.stylelintrc
  frontend/src/apis/github.ts
  frontend/src/components/PairRoomOnboarding/CreateBranchInput/CreateBranchInput.styles.ts
  frontend/src/components/PairRoomOnboarding/CreateBranchInput/CreateBranchInput.tsx
  frontend/src/components/PairRoomOnboarding/CreateBranchModal/CreateBranchModal.styles.ts
  frontend/src/components/PairRoomOnboarding/CreateBranchModal/CreateBranchModal.tsx
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.styles.ts
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.tsx
  frontend/src/components/PairRoomOnboarding/MissionSettingSection/MissionSettingSection.styles.ts
  frontend/src/components/PairRoomOnboarding/MissionSettingSection/MissionSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
  frontend/src/components/PairRoomOnboarding/PairRoomSettingSection/PairRoomSettingSection.styles.ts
  frontend/src/components/PairRoomOnboarding/PairRoomSettingSection/PairRoomSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.styles.ts
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.tsx
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/PairRoomOnboarding/useAutoMoveIndex.ts
  frontend/src/hooks/PairRoomOnboarding/usePairRoomMission.ts
  frontend/src/hooks/common/useDebounce.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/PairRoomOnboarding/useGetBranches.ts
  frontend/src/queries/PairRoomOnboarding/useGetRepositories.ts
  frontend/src/styles/theme.ts
  frontend/src/validations/validateBranchName.ts
  frontend/src/validations/validatePairName.ts
  frontend/src/validations/validateTimerDuration.ts
Labels: ⚙️ refactor

#517 [FE] 빌드 성능 최적화 및 사이트 성능 최적화
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/assets/fonts/Pretendard-Bold.woff2
  frontend/src/assets/fonts/Pretendard-Light.woff2
  frontend/src/assets/fonts/Pretendard-Medium.woff2
  frontend/src/assets/fonts/Pretendard-Regular.woff2
  frontend/src/assets/fonts/Pretendard-SemiBold.woff2
  frontend/src/font.css
  frontend/src/pages/Loading/Loading.styles.ts
  frontend/src/pages/Loading/Loading.tsx
  frontend/src/styles/font.css
  frontend/webpack.common.config.js
  frontend/webpack.development.config.js
  frontend/webpack.production.config.js
  frontend/yarn.lock
Labels: ⚙️ refactor

#503 [FE] 페어룸 투두 리스트 피드백 반영
  frontend/.stylelintrc
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryFilter/CategoryFilter.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryModal/CategoryModal.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryModal/CategoryModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.type.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/PairRoom/TodoListCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/TodoListCard/Header/Header.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoItem/TodoItem.styles.ts
  frontend/src/components/PairRoom/TodoListCard/TodoItem/TodoItem.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoList/TodoList.styles.ts
  frontend/src/components/PairRoom/TodoListCard/TodoList/TodoList.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.styles.ts
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/components/common/CheckBox/CheckBox.styles.ts
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/ToolTipQuestionBox/ToolTipQuestionBox.styles.ts
  frontend/src/components/common/ToolTipQuestionBox/ToolTipQuestionBox.tsx
  frontend/src/components/common/Tooltip/Tooltip.styles.ts
  frontend/src/components/common/Tooltip/Tooltip.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/category/useGetCategories.ts
  frontend/src/validations/validateCategory.ts
Labels: ⚙️ refactor

#527 [BE] 테스트 서버에서 발생하는 CORS 오류 해결
  backend/src/main/java/site/coduo/common/config/WebMvcConfig.java
Labels: 🌋 bug, 🚑 hotfix

#522 [FE] 페어 프로그래밍 설명 페이지 리팩터링
  frontend/src/components/common/ScrollIcon/ScrollIcon.styles.ts
  frontend/src/components/common/ScrollIcon/ScrollIcon.tsx
  frontend/src/pages/HowToPair/HowToPair.styles.ts
  frontend/src/pages/HowToPair/HowToPair.tsx
Labels: ⚙️ refactor

#504 [FE] 코딩해듀오 설명 Docs 페이지 구현
  frontend/src/App.tsx
  frontend/src/assets/images/docs/check-branch-created.png
  frontend/src/assets/images/docs/check-branch-created.webp
  frontend/src/assets/images/docs/clone.png
  frontend/src/assets/images/docs/clone.webp
  frontend/src/assets/images/docs/complete-onboarding.png
  frontend/src/assets/images/docs/complete-onboarding.webp
  frontend/src/assets/images/docs/create-branch.png
  frontend/src/assets/images/docs/create-branch.webp
  frontend/src/assets/images/docs/create-fork.png
  frontend/src/assets/images/docs/create-fork.webp
  frontend/src/assets/images/docs/create-room.png
  frontend/src/assets/images/docs/create-room.webp
  frontend/src/assets/images/docs/fork-repository.png
  frontend/src/assets/images/docs/fork-repository.webp
  frontend/src/assets/images/docs/input-name.png
  frontend/src/assets/images/docs/input-name.webp
  frontend/src/assets/images/docs/input-pair-name.png
  frontend/src/assets/images/docs/input-pair-name.webp
  frontend/src/assets/images/docs/select-driver.png
  frontend/src/assets/images/docs/select-driver.webp
  frontend/src/assets/images/docs/select-mission.png
  frontend/src/assets/images/docs/select-mission.webp
  frontend/src/assets/images/docs/set-role.png
  frontend/src/assets/images/docs/set-role.webp
  frontend/src/assets/images/docs/set-timer.png
  frontend/src/assets/images/docs/set-timer.webp
  frontend/src/assets/images/docs/start-free.png
  frontend/src/assets/images/docs/start-free.webp
  frontend/src/assets/images/docs/start-with-mission.png
  frontend/src/assets/images/docs/start-with-mission.webp
  frontend/src/assets/index.ts
  frontend/src/components/CoduoDocs/DocsImage/DocsImage.stories.tsx
  frontend/src/components/CoduoDocs/DocsImage/DocsImage.styles.ts
  frontend/src/components/CoduoDocs/DocsImage/DocsImage.tsx
  frontend/src/components/CoduoDocs/FloatingSidebar/ContentBox.tsx
  frontend/src/components/CoduoDocs/FloatingSidebar/FloatingSidebar.stories.tsx
  frontend/src/components/CoduoDocs/FloatingSidebar/FloatingSidebar.styles.ts
  frontend/src/components/CoduoDocs/FloatingSidebar/FloatingSidebar.tsx
  frontend/src/components/CoduoDocs/Quote/Quote.styles.ts
  frontend/src/components/CoduoDocs/Quote/Quote.tsx
  frontend/src/components/CoduoDocs/SourceCode/SourceCode.styles.ts
  frontend/src/components/CoduoDocs/SourceCode/SourceCode.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.styles.ts
  frontend/src/constants/coduoDocs.ts
  frontend/src/hooks/common/useHashScroll.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.stories.tsx
  frontend/src/pages/CoduoDocs/CoduoDocs.styles.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.tsx
  frontend/src/pages/CoduoDocs/CoduoDocs.type.ts
  frontend/src/types/types.d.ts
  frontend/webpack.common.config.js
Labels: 🧑‍💻 feat

#532 [BE] 카테고리 길이 제한 변경
  backend/src/main/java/site/coduo/referencelink/domain/Category.java
  backend/src/test/java/site/coduo/referencelink/domain/CategoryTest.java
Labels: ⚙️ refactor

#545 [BE] 카테고리 value 사용 대신 id 사용
  backend/src/main/java/site/coduo/referencelink/controller/CategoryController.java
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java
  backend/src/main/java/site/coduo/referencelink/controller/docs/CategoryDocs.java
  backend/src/main/java/site/coduo/referencelink/controller/docs/ReferenceLinkDocs.java
  backend/src/main/java/site/coduo/referencelink/repository/CategoryEntity.java
  backend/src/main/java/site/coduo/referencelink/repository/CategoryRepository.java
  backend/src/main/java/site/coduo/referencelink/service/CategoryService.java
  backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
  backend/src/main/java/site/coduo/referencelink/service/dto/CategoryUpdateRequest.java
  backend/src/main/java/site/coduo/referencelink/service/dto/ReferenceLinkCreateRequest.java
  backend/src/test/java/site/coduo/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
Labels: ⚙️ refactor

#534 [FE] 사이드바 확장 버튼 리팩터링
  frontend/src/components/PairRoom/PairListCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/PairListCard/Header/Header.tsx
  frontend/src/components/PairRoom/PairRoomCard/Header/Header.styles.ts
Labels: ⚙️ refactor

#530 [BE] 마일스톤 투두 기능에서 발생하는 에러 탐색 및 조치
  backend/src/main/java/site/coduo/pairroom/repository/PairRoomEntity.java
  backend/src/main/java/site/coduo/pairroom/repository/ProdPairRoomRepository.java
  backend/src/main/java/site/coduo/pairroom/service/port/PairRoomRepository.java
  backend/src/main/java/site/coduo/todo/controller/TodoController.java
  backend/src/main/java/site/coduo/todo/controller/docs/TodoDocs.java
  backend/src/main/java/site/coduo/todo/controller/request/CreateTodoRequest.java
  backend/src/main/java/site/coduo/todo/controller/request/UpdateTodoContentRequest.java
  backend/src/main/java/site/coduo/todo/controller/request/UpdateTodoOrderRequest.java
  backend/src/main/java/site/coduo/todo/domain/Todo.java
  backend/src/main/java/site/coduo/todo/domain/TodoSort.java
  backend/src/main/java/site/coduo/todo/exception/InvalidTodoSortException.java
  backend/src/main/java/site/coduo/todo/infrastructure/repository/ProdTodoRepository.java
  backend/src/main/java/site/coduo/todo/repository/TodoEntity.java
  backend/src/main/java/site/coduo/todo/repository/TodoRepository.java
  backend/src/main/java/site/coduo/todo/service/TodoService.java
  backend/src/main/java/site/coduo/todo/service/port/TodoRepository.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/pairroom/mock/FakePairRoomRepository.java
  backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoSortTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoTest.java
  backend/src/test/java/site/coduo/todo/mock/FakeTodoRepository.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: ⚙️ refactor

#552 [FE] 레퍼런스 링크, 카테고리 리팩토링
  frontend/.eslintrc.cjs
  frontend/src/apis/category.ts
  frontend/src/apis/referenceLink.ts
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryFilter/CategoryBox.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryFilter/CategoryFilter.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryFilter/CategoryFilter.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoriesEditor.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoriesEditor.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/IconButton/IconButton.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/IconButton/IconButton.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/Reference/Reference.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/Reference/Reference.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.tsx
  frontend/src/components/common/Dropdown/HiddenDropdown/HiddenDropdown.tsx
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Input/Input.tsx
  frontend/src/hooks/PairRoom/useCategories.ts
  frontend/src/hooks/PairRoom/useEditCategory.ts
  frontend/src/hooks/PairRoom/useReference.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/PairRoom/category/mutation.ts
  frontend/src/queries/PairRoom/category/query.ts
  frontend/src/queries/PairRoom/category/useAddCategory.ts
  frontend/src/queries/PairRoom/category/useDeleteCategory.ts
  frontend/src/queries/PairRoom/category/useGetCategories.ts
  frontend/src/queries/PairRoom/category/useUpdateCategory.ts
  frontend/src/queries/PairRoom/reference/mutation.ts
  frontend/src/queries/PairRoom/reference/query.ts
  frontend/src/queries/PairRoom/useReferenceLinks.ts
  frontend/src/utils/Reference/formatLink.ts
  frontend/src/validations/validateCategory.ts
Labels: ⚙️ refactor

#573 [BE] cors 오류 해결
  backend/src/main/java/site/coduo/common/config/WebMvcConfig.java
Labels: 🌋 bug

#574 [FE] 🚧 내 방 리스트 확인 페이지 구현 (배포 테스트)
  frontend/src/App.tsx
  frontend/src/apis/member.ts
  frontend/src/apis/pairRoom.ts
  frontend/src/apis/signOut.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.styles.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/constants/message.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/hooks/member/useSignUpHandler.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/MyPage/MyPage.styles.ts
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/MyPage/useMyPairRooms.ts
  frontend/src/stores/userStatusStore.ts
  frontend/src/stores/userStore.ts
Labels: 🏗️ infra, 🧑‍💻 feat

#575 [FE] 🚀 내 방 리스트 확인 페이지 구현 (배포 테스트)
  frontend/src/App.tsx
  frontend/src/apis/member.ts
  frontend/src/apis/pairRoom.ts
  frontend/src/apis/signOut.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.styles.ts
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/constants/message.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/hooks/member/useSignUpHandler.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/MyPage/MyPage.styles.ts
  frontend/src/pages/MyPage/MyPage.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/MyPage/useMyPairRooms.ts
  frontend/src/stores/userStatusStore.ts
  frontend/src/stores/userStore.ts
Labels: 🏗️ infra, 🧑‍💻 feat

#583 [FE] 🚧 폰트 로드 로직 변경 (배포 테스트)
  frontend/public/index.html
  frontend/src/styles/font.css
Labels: ⚙️ refactor

#582 [FE] 랜딩 페이지 및 페어룸 온보딩 페이지 반응형 디자인 적용
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.styles.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
Labels: ⚙️ refactor, 🪨 etc

#584 [FE] 🚀 변경 사항 배포 테스트
  frontend/public/index.html
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.styles.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
  frontend/src/styles/font.css
Labels: ⚙️ refactor

#590 [BE] CORS 오류 해결
  backend/src/main/java/site/coduo/common/config/WebMvcConfig.java
Labels: 🌋 bug

#588 [FE] 타이머 시간 동기화
  frontend/src/App.tsx
  frontend/src/apis/pairRoom.ts
  frontend/src/apis/timer.ts
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/PairRoomOnboarding/PairRoomSettingSection/PairRoomSettingSection.tsx
  frontend/src/components/common/Animation/ScrollAnimationContainer.tsx
  frontend/src/components/common/ScrollIcon/ScrollIcon.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/common/useScrollAnimation.ts
  frontend/src/hooks/common/useScrollIcon.ts
  frontend/src/hooks/common/useTitleTime.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/PairRoom/PairRoom.styles.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/Main/useAddPairRoom.ts
  frontend/src/queries/Main/useAddPairRoomHistory.ts
  frontend/src/queries/Main/useGetPairRoomHistory.ts
  frontend/src/queries/PairRoom/useGetPairRoom.ts
  frontend/src/queries/PairRoom/useUpdateDuration.ts
  frontend/src/queries/PairRoom/useUpdatePairRoom.ts
  frontend/src/queries/PairRoomOnboarding/useGetPairRoomInformation.ts
  frontend/src/queries/PairRoomOnboarding/useUpdateRemainingTime.ts
Labels: 🧑‍💻 feat, ⚙️ refactor

#592 [FE] 🚀 타이머 시간 동기화
  frontend/src/App.tsx
  frontend/src/apis/pairRoom.ts
  frontend/src/apis/timer.ts
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/PairRoomOnboarding/PairRoomSettingSection/PairRoomSettingSection.tsx
  frontend/src/components/common/Animation/ScrollAnimationContainer.tsx
  frontend/src/components/common/ScrollIcon/ScrollIcon.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/common/useScrollAnimation.ts
  frontend/src/hooks/common/useScrollIcon.ts
  frontend/src/hooks/common/useTitleTime.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/PairRoom/PairRoom.styles.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/Main/useAddPairRoom.ts
  frontend/src/queries/Main/useAddPairRoomHistory.ts
  frontend/src/queries/Main/useGetPairRoomHistory.ts
  frontend/src/queries/PairRoom/useGetPairRoom.ts
  frontend/src/queries/PairRoom/useUpdateDuration.ts
  frontend/src/queries/PairRoom/useUpdatePairRoom.ts
  frontend/src/queries/PairRoomOnboarding/useGetPairRoomInformation.ts
  frontend/src/queries/PairRoomOnboarding/useUpdateRemainingTime.ts
Labels: 🏗️ infra, 🧑‍💻 feat, ⚙️ refactor

#597 [FE] 랜딩 페이지 개선 및 폴더 구조 변경
  frontend/src/App.tsx
  frontend/src/components/Landing/HowToPair/HowToPair.styles.ts
  frontend/src/components/Landing/HowToPair/HowToPair.tsx
  frontend/src/hooks/common/useScrollAnimation.ts
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
Labels: 💄 design

#610 [BE] allowedmethods 와일드카드 제거
  backend/src/main/java/site/coduo/common/config/WebMvcConfig.java
Labels: 🌋 bug

#618 [BE] 링크 조회 최적화
  backend/src/main/java/site/coduo/common/config/WebMvcConfig.java
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java
  backend/src/main/java/site/coduo/referencelink/repository/ReferenceLinkRepository.java
  backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
Labels: ⚙️ refactor

#607 [FE] docs 내용 추가
  frontend/src/App.tsx
  frontend/src/components/CoduoDocs/FloatingSidebar/FloatingSidebar.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/common/useHashScroll.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.styles.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.tsx
Labels: ✏️ docs, 🧑‍💻 feat

#627 [FE] 파비콘 변경 및 메타데이터 추가
  frontend/public/coduo_metadata.jpg
  frontend/public/favicon.svg
  frontend/public/index.html
  frontend/public/logo_icon.ico
Labels: 🪨 etc

#630 [FE] 카테고리 버그 수정
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoriesEditor.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/hooks/PairRoom/useCategories.ts
  frontend/src/hooks/PairRoom/useEditCategory.ts
  frontend/src/hooks/common/useInput.ts
Labels: 🌋 bug, 🧑‍💻 feat

#633 [FE] 🚀 테스트 서버 배포
  frontend/public/coduo_metadata.jpg
  frontend/public/favicon.svg
  frontend/public/index.html
  frontend/public/logo_icon.ico
  frontend/src/App.tsx
  frontend/src/components/CoduoDocs/FloatingSidebar/FloatingSidebar.styles.ts
  frontend/src/components/Landing/HowToPair/HowToPair.styles.ts
  frontend/src/components/Landing/HowToPair/HowToPair.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoriesEditor.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/PairRoom/useCategories.ts
  frontend/src/hooks/PairRoom/useEditCategory.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/common/useHashScroll.ts
  frontend/src/hooks/common/useInput.ts
  frontend/src/hooks/common/useScrollAnimation.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.styles.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.tsx
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/queries/PairRoom/useUpdateDuration.ts
Labels: 🏗️ infra

#634 [FE] 🚀 핫픽스 적용 배포 테스트
  frontend/public/favicon.ico
  frontend/public/index.html
Labels: 🌋 bug

#636 [FE] 🚀 메타 데이터 이미지 경로 수정
  frontend/public/index.html
Labels: 🏗️ infra

#637 [FE] 카테고리 수정
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/hooks/PairRoom/useEditCategory.ts
  frontend/src/validations/validateCategory.ts
Labels: 🧑‍💻 feat

#639 [FE] 🚀 메타 데이터 이미지 경로 수정
  frontend/public/index.html
  frontend/webpack.common.config.js
Labels: 🏗️ infra

#641 [FE] 스크롤 아이콘 리팩터링
  frontend/src/components/Landing/HowToPair/HowToPair.tsx
  frontend/src/components/common/ScrollIcon/ScrollIcon.styles.ts
  frontend/src/components/common/ScrollIcon/ScrollIcon.tsx
  frontend/src/hooks/common/useScrollIcon.ts
  frontend/src/pages/Landing/Landing.tsx
Labels: ⚙️ refactor

#643 [FE] SSE 연결이 해제되었을 때 재연결을 시도하는 로직 개선
  frontend/src/hooks/PairRoom/useTimer.ts
Labels: ⚙️ refactor

#645 [FE] 기존 CD 삭제
  .github/workflows/fe_cd-test.yml
Labels: 🏗️ infra

#651 [FE] 🚀 오류 해결을 위한 테스트 서버 배포
  .github/workflows/fe_cd-test.yml
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/apis/member.ts
  frontend/src/components/Landing/HowToPair/HowToPair.tsx
  frontend/src/components/common/ScrollIcon/ScrollIcon.styles.ts
  frontend/src/components/common/ScrollIcon/ScrollIcon.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/common/useScrollIcon.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/queries/PairRoom/useTodos.ts
Labels: 🏗️ infra

#652 [FE] 🔖 오류 해결을 위한 운영 서버 배포
  .github/workflows/fe_cd-test.yml
  frontend/public/coduo_metadata.jpg
  frontend/public/favicon.ico
  frontend/public/favicon.svg
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/apis/member.ts
  frontend/src/components/CoduoDocs/FloatingSidebar/FloatingSidebar.styles.ts
  frontend/src/components/Landing/HowToPair/HowToPair.styles.ts
  frontend/src/components/Landing/HowToPair/HowToPair.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/CategoryDropdown/CategoryDropdown.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoriesEditor.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoriesEditor/CategoryItem/ReadonlyCategoryItem/ReadonlyCategoryItem.tsx
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/Header/Header.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/ScrollIcon/ScrollIcon.styles.ts
  frontend/src/components/common/ScrollIcon/ScrollIcon.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/PairRoom/useCategories.ts
  frontend/src/hooks/PairRoom/useEditCategory.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/common/useHashScroll.ts
  frontend/src/hooks/common/useInput.ts
  frontend/src/hooks/common/useScrollAnimation.ts
  frontend/src/hooks/common/useScrollIcon.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/CoduoDocs/CoduoDocs.styles.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.tsx
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/queries/PairRoom/useTodos.ts
  frontend/src/queries/PairRoom/useUpdateDuration.ts
  frontend/src/types/types.d.ts
  frontend/src/validations/validateCategory.ts
  frontend/webpack.common.config.js
Labels: 🏗️ infra

#656 [FE] 내 방 리스트 확인 페이지 구현
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/pages/MyPage/MyPage.styles.ts
  frontend/src/pages/MyPage/MyPage.tsx
Labels: 🧑‍💻 feat, ⚙️ refactor

#657 [FE] 🚀 마이 페이지 배포를 위한 테스트 서버 배포
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/pages/MyPage/MyPage.styles.ts
  frontend/src/pages/MyPage/MyPage.tsx
Labels: 🏗️ infra

#658 [FE] 🔖 운영 서버 배포
  frontend/src/components/MyPage/PairRoomButton/PairRoomButton.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/pages/MyPage/MyPage.styles.ts
  frontend/src/pages/MyPage/MyPage.tsx
Labels: 🏗️ infra
