Repository woowacourse-teams/2024-coduo, pull requests merged in 2024-08, with the labels that each got.

#206 [FE] 헤더 리팩토링
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
Labels: ⚙️ refactor

#209 [FE] UPPER_CASE로 작성된 css 상수들 camelCase로 수정
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.tsx
  frontend/src/components/PairRoomOnBoarding/TimerSettingSection/TimerSettingSection.tsx
  frontend/src/components/common/Button/Button.styles.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Button/Button.type.ts
  frontend/src/components/common/Modal/Modal.stories.tsx
  frontend/src/components/common/Modal/Modal.styles.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/Modal.type.ts
  frontend/src/hooks/Main/usePairNameInputs.test.tsx
  frontend/src/pages/Main/Main.tsx
Labels: ⚙️ refactor

#212 [FE]input 리팩터링
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/styles/theme.ts
Labels: ⚙️ refactor

#211 [FE] 페어룸 페이지에서 필요 없는 요소들 제거
  frontend/src/components/PairRoom/MemoCard/MemoCard.stories.tsx
  frontend/src/components/PairRoom/MemoCard/MemoCard.tsx
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.stories.tsx
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
Labels: ⚙️ refactor

#213 [FE] Placeholder 색 변경
  frontend/src/components/common/Input/Input.styles.ts
Labels: ⚙️ refactor

#215 [FE] API 요청 로직 리팩토링
  frontend/src/apis/fetcher.ts
  frontend/src/apis/pairName.ts
  frontend/src/apis/roomCode.ts
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreate/PairRoomCreate.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceItem.tsx
  frontend/src/hooks/Main/usePairNameInputs.ts
  frontend/src/hooks/common/useInput.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/PairRoom/useAddPairRoom.ts
  frontend/src/queries/PairRoom/useGetPairRoomInformation.ts
  frontend/src/queries/PairRoom/useReferenceLinks.ts
Labels: ⚙️ refactor

#218 [FE] 타이머 설정 제거
  frontend/src/components/PairRoomOnBoarding/FooterButtons/FooterButtons.tsx
  frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.stories.tsx
  frontend/src/components/PairRoomOnBoarding/ProgressBar/ProgressBar.tsx
  frontend/src/constants/PairRoomOnboarding/step.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.type.ts
Labels: ⚙️ refactor

#224 [FE] 타이머가 끝날 경우 브라우저 소리 및 알림으로 사용자에게 알려주도록 구현
  frontend/public/favicon.svg
  frontend/public/index.html
  frontend/src/assets/audio/alarm_sound.mp3
  frontend/src/assets/index.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts
  frontend/src/components/common/Button/Button.styles.ts
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/common/useNotification.ts
  frontend/src/types/types.d.ts
  frontend/webpack.config.js
Labels: 🧑‍💻 feat

#226 [FE] Toast 컴포넌트 구현
  frontend/package.json
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.styles.ts
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/ToastList/ToastList.styles.ts
  frontend/src/components/common/ToastList/ToastList.tsx
  frontend/src/stores/toastStore.ts
  frontend/yarn.lock
Labels: 🧑‍💻 feat

#223 [FE] 북마크 컴포넌트 구현
  frontend/src/apis/referenceLink.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceItem.tsx
  frontend/src/components/common/Bookmark/Bookmark.styles.ts
  frontend/src/components/common/Bookmark/Bookmark.tsx
  frontend/src/components/common/Button/Button.styles.ts
  frontend/src/constants/message.ts
  frontend/src/queries/PairRoom/useReferenceLinks.ts
Labels: 🧑‍💻 feat

#228 [ALL] 코딩해듀오 소개글 추가
  README.md
Labels: ✏️ docs

#232 [BE] 전체 API Prefix 추가
  backend/.gitignore
  backend/src/main/java/site/coduo/common/controller/CommonController.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkController.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
Labels: ⚙️ refactor

#250 [FE] 페어룸 페이지 반응형 디자인 개선
  frontend/src/components/PairRoom/PairListCard/PairListCard.styles.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/components/PairRoom/PairRoomCard/PairRoomCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts
  frontend/src/pages/Layout.styles.ts
  frontend/src/pages/Layout.tsx
  frontend/src/pages/PairRoom/PairRoom.styles.tsx
Labels: ⚙️ refactor

#248 [FE] Sentry로 에러 모니터링 및 디버깅 구현
  frontend/.gitignore
  frontend/package.json
  frontend/src/index.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🏗️ infra

#253 [FE] 현재 alert로 구성된 기능을 Toast 컴포넌트로 변경
  frontend/src/components/common/ToastList/ToastList.styles.ts
  frontend/src/components/common/ToastList/ToastList.tsx
  frontend/src/hooks/common/useCopyClipboard.ts
  frontend/src/pages/Layout.tsx
  frontend/src/queries/PairRoom/useAddPairRoom.ts
  frontend/src/queries/PairRoom/useReferenceLinks.ts
Labels: ⚙️ refactor

#254 [ALL] Dev Branch CI 스크립트 수정
  .github/workflows/be-cd.yml
  .github/workflows/be-ci.yml
  .github/workflows/be_ci.yml
  backend/.gitignore
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
Labels: 🏗️ infra

#263 [BE] 서버 로깅 정책 수립 및 시스템 구축
  backend/src/main/java/site/coduo/common/controller/CommonErrorController.java
  backend/src/main/resources/logback-spring.xml
Labels: 🏗️ infra

#267 [FE] Sentry 및 webpack 설정
  frontend/.gitignore
  frontend/package.json
  frontend/src/apis/fetcher.ts
  frontend/src/index.tsx
  frontend/webpack.common.config.js
  frontend/webpack.development.config.js
  frontend/webpack.production.config.js
  frontend/yarn.lock
Labels: 🏗️ infra, 🚔 policy

#260 [FE] 페어 프로그래밍 안내문 페이지 구현
  frontend/src/App.tsx
  frontend/src/pages/HowToPair/HowToPair.styles.ts
  frontend/src/pages/HowToPair/HowToPair.tsx
Labels: 🧑‍💻 feat

#283 [FE] CD 설정
  .github/workflows/fe_cd-test.yml
  frontend/.gitignore
  frontend/Dockerfile
Labels: 🏗️ infra

#287 [FE] 🚑 Dockerfile 명령어 오류 수정
  .github/workflows/fe_cd-test.yml
  frontend/Dockerfile
Labels: 🚑 hotfix

#289 [FE] 🚑 Dockerfile과 CD 파일에서 공통된 로직 제거
  .github/workflows/fe_cd-test.yml
Labels: 🚑 hotfix

#280 [BE] 로그백 설정 추가
  .github/workflows/be_cd-test.yml
  .gitignore
  backend/Dockerfile
  backend/be_docker-compose.test.yml
  backend/src/main/java/site/coduo/common/controller/CommonController.java
  backend/src/main/java/site/coduo/common/controller/CommonErrorController.java
  backend/src/main/resources/logback-spring.xml
Labels: ✏️ docs, 🏗️ infra

#281 [BE] test branch docker compose 수정
  .github/workflows/be_cd-test.yml
  backend/be_app-docker-compose.yml
  backend/src/main/resources/logback-spring.xml
Labels: 🏗️ infra

#286 [BE] API 문서 경로 수정
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
Labels: ✏️ docs

#292 [BE] 레퍼런스링크 disabled 테스트 수정
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
Labels: ⚙️ refactor

#294 테스트 서버 배포
  .github/workflows/be_cd-test.yml
  .gitignore
  backend/be_docker-compose.test.yml
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
Labels: 🏗️ infra

#299 [BE] Spring Boot 메트릭 모니터링 환경 구축
  backend/be_docker-compose.test.yml
  backend/build.gradle
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
Labels: 🏗️ infra

#301 [BE] 테스트 서버 배포
  backend/be_docker-compose.test.yml
  backend/build.gradle
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-test.yml
Labels: 🏗️ infra

#303 [FE] 🚀 CD 테스트용 2차 배포
  .github/workflows/fe_cd-test.yml
  frontend/Dockerfile
Labels: 🏗️ infra

#312 [FE] 🚑 방 생성하기 모달 오류 해결
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
Labels: 🌋 bug

#291 [FE] GA 초기 설정
  frontend/.eslintrc.cjs
  frontend/package.json
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/ToastList/ToastList.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/index.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/PairRoom/useReferenceLinks.ts
  frontend/yarn.lock
Labels: ✏️ docs, 🧑‍💻 feat

#313 [FE] 🚀 GA 초기 설정 적용
  frontend/.eslintrc.cjs
  frontend/package.json
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/ToastList/ToastList.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/index.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/PairRoom/useReferenceLinks.ts
  frontend/yarn.lock
Labels: 🧑‍💻 feat

#315 [FE] 🚑 CI 타겟에서 FE/test 제거
  .github/workflows/fe-CI.yml
Labels: 🌋 bug, 🏗️ infra, 🚑 hotfix

#300 [FE] 핵심 기능에 대한 테스트 추가
  .github/workflows/fe_cd-test.yml
  frontend/Dockerfile
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/common/useCopyClipboard.test.ts
  frontend/src/hooks/common/useInput.test.ts
Labels: 🧪 test

#274 [FE] 미션 시작 기능 구현
  .vscode/settings.json
  frontend/.eslintrc.cjs
  frontend/package.json
  frontend/src/apis/github.ts
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/StartMission/MissionRepository.tsx
  frontend/src/components/PairRoom/StartMission/StartMission.styles.ts
  frontend/src/components/PairRoom/StartMission/StartMission.tsx
  frontend/src/components/PairRoomOnboarding/ProgressBar/ProgressBar.tsx
  frontend/src/components/common/ToastList/ToastList.tsx
  frontend/src/constants/PairRoomOnboarding/step.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.type.ts
  frontend/src/queries/github/useCreateBranch.ts
  frontend/src/queries/github/useGetBranches.ts
  frontend/src/queries/github/useGetRepositories.ts
  frontend/yarn.lock
Labels: 🧑‍💻 feat

#320 [FE] 미션 시작 기능 및 추가 리팩토링
  .github/workflows/fe_cd-test.yml
  .vscode/settings.json
  frontend/.eslintrc.cjs
  frontend/package.json
  frontend/src/apis/github.ts
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/StartMission/MissionRepository.tsx
  frontend/src/components/PairRoom/StartMission/StartMission.styles.ts
  frontend/src/components/PairRoom/StartMission/StartMission.tsx
  frontend/src/components/PairRoomOnboarding/ProgressBar/ProgressBar.tsx
  frontend/src/components/common/ToastList/ToastList.tsx
  frontend/src/constants/PairRoomOnboarding/step.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.type.ts
  frontend/src/queries/github/useCreateBranch.ts
  frontend/src/queries/github/useGetBranches.ts
  frontend/src/queries/github/useGetRepositories.ts
  frontend/yarn.lock
Labels: 🌋 bug, 🧑‍💻 feat

#322 [FE] Git auth env 네이밍 변경
  frontend/src/apis/github.ts
Labels: 🌋 bug

#323 [FE] 🚀 env 네이밍 수정
  frontend/src/apis/github.ts
Labels: 🌋 bug

#325 [FE] 🚀 github api 로직 제거
  .github/workflows/fe-CI.yml
  .github/workflows/pull_request.yml
  .github/workflows/review_submit_notification.yml
  frontend/Dockerfile
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/constants/pairRoomModalInfo.ts
  frontend/src/hooks/Main/usePairNameInputs.ts
  frontend/src/hooks/common/useCopyClipboard.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/PairRoom/useGetPairRoomInformation.ts
Labels: 🌋 bug, 🚑 hotfix

#327 [FE] 브랜치 생성 로직 재 추가
  frontend/src/components/PairRoom/StartMission/StartMission.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/github/useGetBranches.ts
Labels: 🌋 bug, 🧑‍💻 feat

#328 [FE] 방 참가하기 모달 버그 해결
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/queries/PairRoom/useGetPairRoomInformation.ts
Labels: 🌋 bug

#338 [FE] 페어 프로그래밍 안내 모달 추가
  frontend/src/components/PairRoomOnboarding/HowToPairModal/HowToPairModal.styles.ts
  frontend/src/components/PairRoomOnboarding/HowToPairModal/HowToPairModal.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
Labels: 🧑‍💻 feat

#339 [FE]🚀 3차 마일스톤 최종 배포
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/StartMission/StartMission.tsx
  frontend/src/components/PairRoomOnboarding/HowToPairModal/HowToPairModal.styles.ts
  frontend/src/components/PairRoomOnboarding/HowToPairModal/HowToPairModal.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/PairRoom/useGetPairRoomInformation.ts
  frontend/src/queries/github/useGetBranches.ts
Labels: 🧑‍💻 feat, 🚑 hotfix

#342 [FE] 오타 수정
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.tsx
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.tsx
  frontend/src/components/PairRoomOnboarding/HowToPairModal/HowToPairModal.tsx
  frontend/src/components/PairRoomOnboarding/RoleSettingSection/RoleSettingSection.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
Labels: 🪨 etc

#343 [FE] 에러 페이지 구현
  frontend/src/App.tsx
  frontend/src/pages/Error/PageNotFound.styles.ts
  frontend/src/pages/Error/PageNotFound.tsx
Labels: 🧑‍💻 feat

#356 [FE] Stylelint 규칙 변경
  frontend/.stylelintrc
  frontend/package.json
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.styles.ts
  frontend/src/components/PairRoom/PairListCard/DeleteButton/DeleteButton.styles.ts
  frontend/src/components/PairRoom/PairListCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.styles.ts
  frontend/src/components/PairRoom/PairListCard/PairListSection/PairListSection.styles.ts
  frontend/src/components/PairRoom/PairListCard/RoomCodeSection/RoomCodeSection.styles.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/components/PairRoom/PairRoomCard/Header/Header.styles.ts
  frontend/src/components/PairRoom/PairRoomCard/PairRoomCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/Bookmark/Bookmark.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.styles.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.styles.ts
  frontend/src/components/PairRoom/StartMission/StartMission.styles.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts
  frontend/src/components/PairRoom/TodoListCard/TodoItem/TodoItem.styles.ts
  frontend/src/components/PairRoom/TodoListCard/TodoList/TodoList.styles.ts
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.styles.ts
  frontend/src/components/PairRoomOnboarding/HowToPairModal/HowToPairModal.styles.ts
  frontend/src/components/PairRoomOnboarding/InformationBox/InformationBox.styles.ts
  frontend/src/components/PairRoomOnboarding/ProgressBar/ProgressBar.styles.ts
  frontend/src/components/PairRoomOnboarding/RoleSettingSection/RoleSettingSection.styles.ts
  frontend/src/components/PairRoomOnboarding/TimerSettingSection/TimerSettingSection.styles.ts
  frontend/src/components/common/Button/Button.styles.ts
  frontend/src/components/common/CheckBox/CheckBox.styles.ts
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.styles.tsx
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Modal/Body/Body.styles.ts
  frontend/src/components/common/Modal/CloseButton/CloseButton.styles.ts
  frontend/src/components/common/Modal/Footer/Footer.styles.ts
  frontend/src/components/common/Modal/Header/Header.styles.ts
  frontend/src/components/common/Modal/Modal.styles.ts
  frontend/src/components/common/Toast/Toast.styles.ts
  frontend/src/components/common/ToastList/ToastList.styles.ts
  frontend/src/pages/HowToPair/HowToPair.styles.ts
  frontend/src/pages/Layout.styles.ts
  frontend/src/pages/Main/Main.styles.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
  frontend/yarn.lock
Labels: ⚙️ refactor, 🚔 policy

#358 [FE] 🚑️ Onboarding 에서 미션 단계 제거
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
Labels: 🚑 hotfix

#344 [FE] Spinner 구현 및 페어룸 생성 모달 오류 수정
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreate/PairRoomCreate.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.stories.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateComplete/PairRoomCreateComplete.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/PairRoom/StartMission/StartMission.tsx
  frontend/src/components/common/Spinner/Spinner.stories.tsx
  frontend/src/components/common/Spinner/Spinner.styles.ts
  frontend/src/components/common/Spinner/Spinner.tsx
  frontend/src/components/common/Spinner/Spinner.type.ts
  frontend/src/hooks/common/useCopyClipboard.ts
  frontend/src/pages/Error/PageNotFound.styles.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
Labels: 🌋 bug, 🧑‍💻 feat, ⚙️ refactor

#369 [FE] 깃허브 로그인 구현
  frontend/src/App.tsx
  frontend/src/apis/oauth.ts
  frontend/src/apis/signOut.ts
  frontend/src/assets/images/github-mark-white.png
  frontend/src/assets/images/github-mark.png
  frontend/src/assets/index.ts
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/constants/message.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/font.css
  frontend/src/hooks/Main/usePairNameInputs.ts
  frontend/src/hooks/member/useSignInHandler.ts
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/pages/Main/Main.styles.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/SignUp/SignUp.styles.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/Member/Github/useSignIn.ts
  frontend/src/queries/Member/Github/useSignUp.ts
  frontend/src/queries/Member/useSignOut.ts
  frontend/src/stores/userStatusStore.ts
  frontend/src/styles/Global.style.tsx
  frontend/src/types/types.d.ts
  frontend/src/validations/common/validatePairName.ts
  frontend/tsconfig.json
Labels: 🏗️ infra, 🧑‍💻 feat, 🚔 policy

#373 [FE] 회원가입 테스트
  frontend/src/App.tsx
  frontend/src/apis/fetcher.ts
  frontend/src/apis/oauth.ts
  frontend/src/components/common/Spinner/Spinner.styles.ts
  frontend/src/hooks/member/useSignInHandler.ts
  frontend/src/pages/Callback/Callback.styles.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/Member/Github/useSignUp.ts
Labels: 🌋 bug, 🏗️ infra, 🧑‍💻 feat

#374 [FE] 회원가입 기능 테스트 배포
  frontend/src/App.tsx
  frontend/src/apis/fetcher.ts
  frontend/src/apis/oauth.ts
  frontend/src/components/common/Spinner/Spinner.styles.ts
  frontend/src/hooks/member/useSignInHandler.ts
  frontend/src/pages/Callback/Callback.styles.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/Member/Github/useSignUp.ts
Labels: 🌋 bug, 🏗️ infra, 🧑‍💻 feat

#387 [BE] 페어룸 조회 응답 바디의 timerDuration 타입 long에서 Long으로 변경
  backend/src/main/java/site/coduo/pairroom/dto/PairRoomReadResponse.java
Labels: 🌋 bug

#389 [BE] timer 수정 API 변경
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
Labels: ⚙️ refactor

#390 [FE] 로그인/회원가입 로직 수정 및 경로 정상화
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/pages/Callback/Callback.styles.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/SignUp/SignUp.styles.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/Member/Github/useSignIn.ts
  frontend/src/queries/Member/Github/useSignUp.ts
  frontend/src/queries/Member/useSignOut.ts
Labels: 🌋 bug, 🏗️ infra, ⚙️ refactor

#391 [FE] 🚀 로그인/회원가입 로직 수정 및 경로 정상화
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/pages/Callback/Callback.styles.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/SignUp/SignUp.styles.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/Member/Github/useSignIn.ts
  frontend/src/queries/Member/Github/useSignUp.ts
  frontend/src/queries/Member/useSignOut.ts
Labels: 🌋 bug, 🏗️ infra, ⚙️ refactor

#394 [FE] 회원가입 버튼이 handleSignOut 로직과 연결되어 있던 문제 해결
  frontend/src/hooks/member/useSignUpHandler.ts
  frontend/src/pages/SignUp/SignUp.tsx
Labels: 🌋 bug

#395 [FE] 회원가입 버튼이 handleSignOut 로직과 연결되어 있던 문제 해결
  frontend/src/hooks/member/useSignUpHandler.ts
  frontend/src/pages/SignUp/SignUp.tsx
Labels: 🌋 bug

#396 [FE] 로그아웃 시 바로 적용이 되지 않던 오류 해결, 로그아웃 후 재로그인이 되지 않던 오류 해결
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/pages/Callback/Callback.tsx
Labels: 🌋 bug

#397 [FE] 로그아웃이 바로 적용되지 않던 문제 해결, 로그아웃 후 재로그인이 되지 않던 문제 해결
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/pages/Callback/Callback.tsx
Labels: 🌋 bug

#399 [FE] 필요 없는 json 파싱 로직 제거
  frontend/src/apis/signOut.ts
Labels: 🌋 bug

#400 [FE] 🚀 필요 없는 json 파싱 로직 제거
  frontend/src/apis/signOut.ts
Labels: 🌋 bug

#402 [BE] 카테고리 문서화 및 중복 검증 로직 수정
  backend/src/main/java/site/coduo/referencelink/controller/CategoryController.java
  backend/src/main/java/site/coduo/referencelink/controller/docs/CategoryDocs.java
  backend/src/main/java/site/coduo/referencelink/controller/docs/ReferenceLinkDocs.java
  backend/src/main/java/site/coduo/referencelink/repository/CategoryRepository.java
  backend/src/main/java/site/coduo/referencelink/service/CategoryService.java
Labels: 🌋 bug, ✏️ docs

#406 [BE] 페어룸 API 문서 수정
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
Labels: ✏️ docs

#412 [FE] 창을 닫았다 다시 열어도 로그인이 유지되도록 구현 및 버그 해결
  frontend/src/App.tsx
  frontend/src/apis/oauth.ts
  frontend/src/constants/message.ts
  frontend/src/hooks/member/useSignUpHandler.ts
  frontend/src/stores/userStatusStore.ts
Labels: 🌋 bug, 🧑‍💻 feat

#413 [FE] 🚀 로그인 유지 구현 및 버그 해결
  frontend/src/App.tsx
  frontend/src/apis/oauth.ts
  frontend/src/constants/message.ts
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/hooks/member/useSignUpHandler.ts
  frontend/src/stores/userStatusStore.ts
Labels: 🌋 bug, 🧑‍💻 feat

#418 [BE] 스웨거 API prefix 추가
  backend/src/main/resources/application-test.yml
Labels: 🌋 bug

#420 [FE] 랜딩 페이지와 메인 페이지 분리
  frontend/src/App.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/SignUp/SignUp.tsx
Labels: 🌋 bug, 🧑‍💻 feat

#421 [FE] 🚀 랜딩 페이지와 메인 페이지 분리
  frontend/src/App.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/SignUp/SignUp.tsx
Labels: 🌋 bug, 🧑‍💻 feat

#422 [FE] BF 캐싱 문제 해결 테스트
  frontend/src/App.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/common/usePreventBackNavigation.ts
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/hooks/member/useSignUpHandler.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.tsx
Labels: 🌋 bug, 🧑‍💻 feat

#423 [FE] 🚀 BF 캐싱 문제 해결 테스트
  frontend/src/App.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/hooks/common/usePreventBackNavigation.ts
  frontend/src/hooks/member/useSignOutHandler.ts
  frontend/src/hooks/member/useSignUpHandler.ts
  frontend/src/pages/Callback/Callback.tsx
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.tsx
Labels: 🌋 bug, 🧑‍💻 feat

#428 [BE] 마일스톤 TODO 아이템 CRUD API 구현
  backend/src/main/java/site/coduo/pairroom/domain/PairRoom.java
  backend/src/main/java/site/coduo/pairroom/repository/ProdPairRoomRepository.java
  backend/src/main/java/site/coduo/pairroom/service/port/PairRoomRepository.java
  backend/src/main/java/site/coduo/todo/controller/TodoController.java
  backend/src/main/java/site/coduo/todo/controller/docs/TodoDocs.java
  backend/src/main/java/site/coduo/todo/controller/request/CreateTodoRequest.java
  backend/src/main/java/site/coduo/todo/controller/request/UpdateTodoContentRequest.java
  backend/src/main/java/site/coduo/todo/controller/request/UpdateTodoOrderRequest.java
  backend/src/main/java/site/coduo/todo/controller/response/GetTodoResponse.java
  backend/src/main/java/site/coduo/todo/domain/Todo.java
  backend/src/main/java/site/coduo/todo/domain/TodoChecked.java
  backend/src/main/java/site/coduo/todo/domain/TodoContent.java
  backend/src/main/java/site/coduo/todo/domain/TodoSort.java
  backend/src/main/java/site/coduo/todo/domain/exception/InvalidTodoArgumentException.java
  backend/src/main/java/site/coduo/todo/domain/exception/InvalidTodoContentException.java
  backend/src/main/java/site/coduo/todo/domain/exception/InvalidTodoSortException.java
  backend/src/main/java/site/coduo/todo/domain/exception/InvalidUpdatedTodoSortException.java
  backend/src/main/java/site/coduo/todo/domain/exception/TodoException.java
  backend/src/main/java/site/coduo/todo/domain/exception/TodoNotFoundException.java
  backend/src/main/java/site/coduo/todo/infrastructure/repository/ProdTodoRepository.java
  backend/src/main/java/site/coduo/todo/infrastructure/repository/TodoEntity.java
  backend/src/main/java/site/coduo/todo/infrastructure/repository/TodoJpaRepository.java
  backend/src/main/java/site/coduo/todo/service/TodoService.java
  backend/src/main/java/site/coduo/todo/service/port/TodoRepository.java
  backend/src/test/java/site/coduo/pairroom/mock/FakePairRoomRepository.java
  backend/src/test/java/site/coduo/todo/domain/TodoCheckedTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoContentTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoSortTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoTest.java
  backend/src/test/java/site/coduo/todo/mock/FakeTodoRepository.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: 🧑‍💻 feat

#409 [BE] 페어룸 상태 저장 기능 완료
  backend/src/main/java/site/coduo/pairroom/dto/PairRoomReadResponse.java
  backend/src/main/java/site/coduo/pairroom/dto/TimerDurationCreateRequest.java
  backend/src/main/java/site/coduo/pairroomhistory/controller/PairRoomHistoryController.java
  backend/src/main/java/site/coduo/pairroomhistory/controller/docs/PairRoomHistoryDocs.java
  backend/src/main/java/site/coduo/pairroomhistory/domain/PairRoomHistory.java
  backend/src/main/java/site/coduo/pairroomhistory/dto/PairRoomHistoryCreateRequest.java
  backend/src/main/java/site/coduo/pairroomhistory/dto/PairRoomHistoryReadResponse.java
  backend/src/main/java/site/coduo/pairroomhistory/dto/PairRoomHistoryUpdateRequest.java
  backend/src/main/java/site/coduo/pairroomhistory/exception/PairRoomHistoryException.java
  backend/src/main/java/site/coduo/pairroomhistory/exception/PairRoomHistoryNotFoundException.java
  backend/src/main/java/site/coduo/pairroomhistory/repository/PairRoomHistoryEntity.java
  backend/src/main/java/site/coduo/pairroomhistory/repository/PairRoomHistoryRepository.java
  backend/src/main/java/site/coduo/pairroomhistory/service/PairRoomHistoryService.java
  backend/src/main/java/site/coduo/referencelink/controller/docs/ReferenceLinkDocs.java
  backend/src/test/java/site/coduo/acceptance/AcceptanceFixture.java
  backend/src/test/java/site/coduo/acceptance/PairRoomHistoryAcceptanceTest.java
  backend/src/test/java/site/coduo/pairroomhistory/repository/PairRoomHistoryRepositoryTest.java
  backend/src/test/java/site/coduo/pairroomhistory/service/PairRoomHistoryServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
  backend/src/test/java/site/coduo/utils/CascadeCleaner.java
Labels: 🧑‍💻 feat

#434 [BE] 에러 핸들링 리팩터링
  backend/src/main/java/site/coduo/common/controller/CommonErrorController.java
  backend/src/main/java/site/coduo/common/exception/CoduoException.java
  backend/src/main/java/site/coduo/member/controller/MemberErrorController.java
  backend/src/main/java/site/coduo/member/exception/MemberException.java
  backend/src/main/java/site/coduo/member/exception/MemberNotFoundException.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomErrorController.java
  backend/src/main/java/site/coduo/pairroom/controller/error/PairRoomApiError.java
  backend/src/main/java/site/coduo/pairroom/exception/DuplicatePairNameException.java
  backend/src/main/java/site/coduo/pairroom/exception/InvalidNameFormatException.java
  backend/src/main/java/site/coduo/pairroom/exception/PairRoomException.java
  backend/src/main/java/site/coduo/pairroom/exception/PairRoomNotFoundException.java
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkErrorController.java
  backend/src/main/java/site/coduo/referencelink/controller/error/ReferenceLinkApiError.java
  backend/src/main/java/site/coduo/referencelink/exception/ReferenceLinkException.java
  backend/src/main/java/site/coduo/todo/controller/TodoErrorController.java
  backend/src/main/java/site/coduo/todo/controller/error/TodoApiError.java
  backend/src/main/java/site/coduo/todo/domain/Todo.java
  backend/src/main/java/site/coduo/todo/domain/TodoContent.java
  backend/src/main/java/site/coduo/todo/domain/TodoSort.java
  backend/src/main/java/site/coduo/todo/domain/exception/InvalidTodoArgumentException.java
  backend/src/main/java/site/coduo/todo/domain/exception/TodoException.java
  backend/src/main/java/site/coduo/todo/exception/InvalidTodoArgumentException.java
  backend/src/main/java/site/coduo/todo/exception/InvalidTodoContentException.java
  backend/src/main/java/site/coduo/todo/exception/InvalidTodoSortException.java
  backend/src/main/java/site/coduo/todo/exception/InvalidUpdatedTodoSortException.java
  backend/src/main/java/site/coduo/todo/exception/TodoException.java
  backend/src/main/java/site/coduo/todo/exception/TodoNotFoundException.java
  backend/src/main/java/site/coduo/todo/service/TodoService.java
  backend/src/test/java/site/coduo/todo/domain/TodoContentTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoSortTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: ⚙️ refactor

#414 [FE] 타이머 시간 저장 기능 구현
  frontend/src/apis/fetcher.ts
  frontend/src/apis/pairRoom.ts
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoom/PairRoomCard/PairRoomCard.styles.ts
  frontend/src/components/PairRoom/StartMission/StartMission.tsx
  frontend/src/components/PairRoom/TimerCard/TimerCard.styles.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.styles.ts
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/PairRoomOnboarding/FooterButtons/FooterButtons.tsx
  frontend/src/components/PairRoomOnboarding/ProgressBar/ProgressBar.styles.ts
  frontend/src/components/PairRoomOnboarding/ProgressBar/ProgressBar.tsx
  frontend/src/components/PairRoomOnboarding/RoleSelection/RoleSelection.styles.ts
  frontend/src/components/PairRoomOnboarding/RoleSelection/RoleSelection.tsx
  frontend/src/components/PairRoomOnboarding/RoleSettingSection/RoleSettingSection.tsx
  frontend/src/components/PairRoomOnboarding/TimerSelection/TimerSelection.styles.ts
  frontend/src/components/PairRoomOnboarding/TimerSelection/TimerSelection.tsx
  frontend/src/components/PairRoomOnboarding/TimerSettingSection/TimerSettingSection.tsx
  frontend/src/constants/PairRoomOnboarding/step.ts
  frontend/src/constants/message.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.type.ts
  frontend/src/queries/Main/useAddPairRoom.ts
  frontend/src/queries/PairRoom/useGetPairRoomInformation.ts
  frontend/src/queries/PairRoomOnboarding/useAddTimer.ts
  frontend/src/queries/PairRoomOnboarding/useCreateBranch.ts
  frontend/src/queries/PairRoomOnboarding/useGetBranches.ts
  frontend/src/queries/PairRoomOnboarding/useGetPairRoomInformation.ts
  frontend/src/queries/PairRoomOnboarding/useGetRepositories.ts
  frontend/src/utils/PairRoomOnboarding/validate.ts
Labels: 🧑‍💻 feat, ⚙️ refactor

#444 [BE] 스웨거 CORS 오류 해결
  backend/src/main/java/site/coduo/common/config/WebConfig.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
Labels: 🌋 bug

#445 [BE] RestControllerAdvice 수정 및 스웨거 CORS 해결 배포
  backend/src/main/java/site/coduo/common/config/WebConfig.java
  backend/src/main/java/site/coduo/common/controller/CommonErrorController.java
  backend/src/main/java/site/coduo/common/exception/CoduoException.java
  backend/src/main/java/site/coduo/member/controller/MemberErrorController.java
  backend/src/main/java/site/coduo/member/exception/MemberException.java
  backend/src/main/java/site/coduo/member/exception/MemberNotFoundException.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomErrorController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/main/java/site/coduo/pairroom/controller/error/PairRoomApiError.java
  backend/src/main/java/site/coduo/pairroom/exception/DuplicatePairNameException.java
  backend/src/main/java/site/coduo/pairroom/exception/InvalidNameFormatException.java
  backend/src/main/java/site/coduo/pairroom/exception/PairRoomException.java
  backend/src/main/java/site/coduo/pairroom/exception/PairRoomNotFoundException.java
  backend/src/main/java/site/coduo/referencelink/controller/ReferenceLinkErrorController.java
  backend/src/main/java/site/coduo/referencelink/controller/error/ReferenceLinkApiError.java
  backend/src/main/java/site/coduo/referencelink/exception/ReferenceLinkException.java
  backend/src/main/java/site/coduo/todo/controller/TodoErrorController.java
  backend/src/main/java/site/coduo/todo/controller/error/TodoApiError.java
  backend/src/main/java/site/coduo/todo/domain/Todo.java
  backend/src/main/java/site/coduo/todo/domain/TodoContent.java
  backend/src/main/java/site/coduo/todo/domain/TodoSort.java
  backend/src/main/java/site/coduo/todo/domain/exception/InvalidTodoArgumentException.java
  backend/src/main/java/site/coduo/todo/domain/exception/TodoException.java
  backend/src/main/java/site/coduo/todo/exception/InvalidTodoArgumentException.java
  backend/src/main/java/site/coduo/todo/exception/InvalidTodoContentException.java
  backend/src/main/java/site/coduo/todo/exception/InvalidTodoSortException.java
  backend/src/main/java/site/coduo/todo/exception/InvalidUpdatedTodoSortException.java
  backend/src/main/java/site/coduo/todo/exception/TodoException.java
  backend/src/main/java/site/coduo/todo/exception/TodoNotFoundException.java
  backend/src/main/java/site/coduo/todo/service/TodoService.java
  backend/src/test/java/site/coduo/todo/domain/TodoContentTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoSortTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: 🏗️ infra

#453 [BE] 멤버 도메인 swagger 문서화
  backend/src/main/java/site/coduo/member/controller/docs/AuthControllerDocs.java
  backend/src/main/java/site/coduo/member/controller/docs/GithubOAuthControllerDocs.java
  backend/src/main/java/site/coduo/member/controller/docs/MemberControllerDocs.java
  backend/src/main/java/site/coduo/member/service/dto/auth/SignInCheckResponse.java
  backend/src/main/java/site/coduo/member/service/dto/auth/SignInWebResponse.java
  backend/src/main/java/site/coduo/member/service/dto/auth/SignUpRequest.java
  backend/src/main/java/site/coduo/member/service/dto/member/MemberReadResponse.java
  backend/src/main/java/site/coduo/member/service/dto/oauth/GithubOAuthEndpoint.java
  backend/src/main/resources/application.yml
  backend/src/test/java/site/coduo/fake/FixedNonceProvider.java
Labels: ✏️ docs

#455 [BE] 회원 도메인 리팩토링
  backend/.gitignore
  backend/src/main/java/site/coduo/common/config/FilterConfig.java
  backend/src/main/java/site/coduo/common/config/WebMvcConfig.java
  backend/src/main/java/site/coduo/common/config/filter/AccessTokenSessionFilter.java
  backend/src/main/java/site/coduo/common/config/filter/SessionFilter.java
  backend/src/main/java/site/coduo/common/config/filter/SignInCookieFilter.java
  backend/src/main/java/site/coduo/common/config/filter/StateSessionFilter.java
  backend/src/main/java/site/coduo/member/controller/AuthController.java
  backend/src/main/java/site/coduo/member/controller/GithubOAuthController.java
  backend/src/main/java/site/coduo/member/controller/MemberController.java
  backend/src/main/java/site/coduo/member/controller/docs/AuthControllerDocs.java
  backend/src/main/java/site/coduo/member/controller/docs/GithubOAuthControllerDocs.java
  backend/src/main/java/site/coduo/member/controller/docs/MemberControllerDocs.java
  backend/src/main/java/site/coduo/member/controller/dto/auth/SignInCheckResponse.java
  backend/src/main/java/site/coduo/member/controller/dto/auth/SignUpRequest.java
  backend/src/main/java/site/coduo/member/controller/dto/oauth/GithubOAuthEndpoint.java
  backend/src/main/java/site/coduo/member/exception/MemberNotFoundException.java
  backend/src/main/java/site/coduo/member/infrastructure/security/NonceProvider.java
  backend/src/main/java/site/coduo/member/infrastructure/security/UUIDNonceProvider.java
  backend/src/main/java/site/coduo/member/service/AuthService.java
  backend/src/main/java/site/coduo/member/service/GithubOAuthService.java
  backend/src/main/java/site/coduo/member/service/MemberService.java
  backend/src/main/java/site/coduo/member/service/dto/auth/SignInCheckResponse.java
  backend/src/main/java/site/coduo/member/service/dto/auth/SignInCookie.java
  backend/src/main/java/site/coduo/member/service/dto/auth/SignInWebResponse.java
  backend/src/main/java/site/coduo/member/service/dto/auth/SignUpRequest.java
  backend/src/main/java/site/coduo/member/service/dto/member/MemberReadResponse.java
  backend/src/main/java/site/coduo/member/service/dto/oauth/GithubAuthQuery.java
  backend/src/main/java/site/coduo/member/service/dto/oauth/GithubAuthUri.java
  backend/src/main/java/site/coduo/member/service/dto/oauth/GithubCallbackQuery.java
  backend/src/main/java/site/coduo/member/service/dto/oauth/GithubOAuthEndpoint.java
  backend/src/main/java/site/coduo/member/service/dto/oauth/State.java
  backend/src/main/java/site/coduo/referencelink/domain/OpenGraph.java
  backend/src/main/java/site/coduo/referencelink/domain/ReferenceLink.java
  backend/src/main/java/site/coduo/referencelink/domain/Url.java
  backend/src/main/java/site/coduo/referencelink/service/OpenGraphService.java
  backend/src/main/java/site/coduo/referencelink/service/ReferenceLinkService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/site/coduo/acceptance/AuthAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/GithubAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/MemberAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
  backend/src/test/java/site/coduo/common/infrastructure/security/JwtProviderTest.java
  backend/src/test/java/site/coduo/config/TestConfig.java
  backend/src/test/java/site/coduo/fake/FakeJwtProvider.java
  backend/src/test/java/site/coduo/fake/FixedNanceProvider.java
  backend/src/test/java/site/coduo/fake/FixedNonceProvider.java
  backend/src/test/java/site/coduo/member/service/AuthServiceTest.java
  backend/src/test/java/site/coduo/member/service/GithubOAuthServiceTest.java
  backend/src/test/java/site/coduo/member/service/MemberServiceTest.java
  backend/src/test/java/site/coduo/referencelink/domain/ReferenceLinkTest.java
  backend/src/test/java/site/coduo/referencelink/domain/UrlTest.java
  backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
Labels: ⚙️ refactor

#451 [BE] 페어룸 상태 추가 및 상태 변경 api
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/main/java/site/coduo/pairroom/domain/PairRoom.java
  backend/src/main/java/site/coduo/pairroom/domain/PairRoomStatus.java
  backend/src/main/java/site/coduo/pairroom/domain/accesscode/AccessCodeFactory.java
  backend/src/main/java/site/coduo/pairroom/exception/InvalidAccessCodeException.java
  backend/src/main/java/site/coduo/pairroom/exception/InvalidTimerDurationException.java
  backend/src/main/java/site/coduo/pairroom/exception/PairRoomStatusNotFoundException.java
  backend/src/main/java/site/coduo/pairroom/repository/PairRoomRepository.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomCreateRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomCreateResponse.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomDeleteRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomReadRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomReadResponse.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomStatusUpdateRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/TimerDurationCreateRequest.java
  backend/src/test/java/site/coduo/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/PairRoomHistoryAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
  backend/src/test/java/site/coduo/pairroom/domain/AccessCodeFactoryTest.java
  backend/src/test/java/site/coduo/pairroom/domain/PairRoomStatusTest.java
  backend/src/test/java/site/coduo/pairroom/domain/PairRoomTest.java
  backend/src/test/java/site/coduo/pairroom/mock/FakePairRoomRepository.java
  backend/src/test/java/site/coduo/pairroom/repository/PairRoomRepositoryTest.java
  backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
  backend/src/test/java/site/coduo/pairroomhistory/repository/PairRoomHistoryRepositoryTest.java
  backend/src/test/java/site/coduo/pairroomhistory/service/PairRoomHistoryServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: 🧑‍💻 feat

#446 [FE] 페어 프로그래밍 안내 페이지 디자인 수정 및 스크롤 버튼 구현
  frontend/src/assets/images/characters/driver.png
  frontend/src/assets/images/characters/navigator.png
  frontend/src/assets/index.ts
  frontend/src/components/common/Animation/ScrollAnimationContainer.styles.ts
  frontend/src/components/common/Animation/ScrollAnimationContainer.tsx
  frontend/src/components/common/ScrollIcon/ScrollIcon.styles.ts
  frontend/src/components/common/ScrollIcon/ScrollIcon.tsx
  frontend/src/hooks/Scroll/useScrollIcon.ts
  frontend/src/hooks/animations/useScrollAnimation.ts
  frontend/src/pages/HowToPair/HowToPair.styles.ts
  frontend/src/pages/HowToPair/HowToPair.tsx
Labels: 🧑‍💻 feat, ⚙️ refactor

#456 [BE] 카테고리 테스트 추가
  backend/src/main/java/site/coduo/referencelink/domain/Category.java
  backend/src/main/java/site/coduo/referencelink/repository/CategoryEntity.java
  backend/src/test/java/site/coduo/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/site/coduo/fixture/AccessCodeFixture.java
  backend/src/test/java/site/coduo/fixture/PairRoomFixture.java
  backend/src/test/java/site/coduo/pairroom/domain/PairRoomTest.java
  backend/src/test/java/site/coduo/referencelink/domain/CategoryTest.java
  backend/src/test/java/site/coduo/referencelink/service/CategoryServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/ReferenceLinkServiceTest.java
  backend/src/test/java/site/coduo/utils/CascadeCleaner.java
Labels: 🧪 test

#465 [BE] 페어룸 히스토리 CRU 수정 및 페어룸 Delete api 제거
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomController.java
  backend/src/main/java/site/coduo/pairroom/controller/PairRoomErrorController.java
  backend/src/main/java/site/coduo/pairroom/controller/docs/PairRoomDocs.java
  backend/src/main/java/site/coduo/pairroom/controller/error/PairRoomApiError.java
  backend/src/main/java/site/coduo/pairroom/domain/PairRoomStatus.java
  backend/src/main/java/site/coduo/pairroom/exception/InvalidPairRoomStatusException.java
  backend/src/main/java/site/coduo/pairroom/exception/PairRoomStatusNotFoundException.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomCreateRequest.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomReadResponse.java
  backend/src/main/java/site/coduo/pairroomhistory/controller/PairRoomHistoryController.java
  backend/src/main/java/site/coduo/pairroomhistory/controller/PairRoomHistoryErrorController.java
  backend/src/main/java/site/coduo/pairroomhistory/controller/docs/PairRoomHistoryDocs.java
  backend/src/main/java/site/coduo/pairroomhistory/controller/error/PairRoomHistoryApiError.java
  backend/src/main/java/site/coduo/pairroomhistory/domain/PairRoomHistory.java
  backend/src/main/java/site/coduo/pairroomhistory/domain/Timer.java
  backend/src/main/java/site/coduo/pairroomhistory/exception/InvalidTimerException.java
  backend/src/main/java/site/coduo/pairroomhistory/repository/PairRoomHistoryEntity.java
  backend/src/main/java/site/coduo/pairroomhistory/repository/PairRoomHistoryRepository.java
  backend/src/main/java/site/coduo/pairroomhistory/service/PairRoomHistoryService.java
  backend/src/main/java/site/coduo/pairroomhistory/service/dto/PairRoomHistoryCreateRequest.java
  backend/src/main/java/site/coduo/pairroomhistory/service/dto/PairRoomHistoryReadResponse.java
  backend/src/main/java/site/coduo/pairroomhistory/service/dto/PairRoomHistoryTimerDurationUpdateRequest.java
  backend/src/main/java/site/coduo/pairroomhistory/service/dto/PairRoomHistoryTimerRemainingTimeUpdateRequest.java
  backend/src/test/java/site/coduo/acceptance/CategoryAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/PairRoomAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/PairRoomHistoryAcceptanceTest.java
  backend/src/test/java/site/coduo/acceptance/ReferenceAcceptanceTest.java
  backend/src/test/java/site/coduo/fixture/PairRoomFixture.java
  backend/src/test/java/site/coduo/pairroom/domain/PairRoomStatusTest.java
  backend/src/test/java/site/coduo/pairroom/domain/PairRoomTest.java
  backend/src/test/java/site/coduo/pairroom/repository/PairRoomRepositoryTest.java
  backend/src/test/java/site/coduo/pairroom/service/PairRoomServiceTest.java
  backend/src/test/java/site/coduo/pairroomhistory/domain/TimerTest.java
  backend/src/test/java/site/coduo/pairroomhistory/repository/PairRoomHistoryRepositoryTest.java
  backend/src/test/java/site/coduo/pairroomhistory/service/PairRoomHistoryServiceTest.java
  backend/src/test/java/site/coduo/referencelink/service/OpenGraphServiceTest.java
  backend/src/test/java/site/coduo/todo/domain/TodoTest.java
  backend/src/test/java/site/coduo/todo/service/TodoServiceTest.java
Labels: 🧑‍💻 feat

#469 [BE] TODO API 수정
  backend/src/main/java/site/coduo/todo/controller/TodoController.java
  backend/src/main/java/site/coduo/todo/controller/request/CreateTodoRequest.java
  backend/src/main/java/site/coduo/todo/controller/request/UpdateTodoContentRequest.java
  backend/src/main/java/site/coduo/todo/infrastructure/repository/TodoEntity.java
Labels: 🌋 bug

#452 [FE] 공통 Tooltip 구현
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.tsx
  frontend/src/components/PairRoom/PairRoomCard/Header/Header.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/components/common/Tooltip/ToolTipQuestionBox.tsx
  frontend/src/components/common/Tooltip/Tooltip.styles.ts
  frontend/src/components/common/Tooltip/Tooltip.tsx
  frontend/src/components/common/Tooltip/Tooltip.type.ts
  frontend/src/pages/Landing/Landing.tsx
Labels: 🧑‍💻 feat

#472 [FE] 방 만들기 모달에 미션용 방 선택 기능 구현 & 페어룸 히스토리 API 연동
  frontend/src/App.tsx
  frontend/src/apis/pairRoom.ts
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreate/PairRoomCreate.tsx
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.styles.ts
  frontend/src/components/Main/PairRoomCreateModal/PairRoomCreateModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/AddReferenceForm/AddReferenceForm.tsx
  frontend/src/components/PairRoom/StartMission/MissionRepository.tsx
  frontend/src/components/PairRoom/StartMission/StartMission.tsx
  frontend/src/components/PairRoom/TimerCard/TimerEditPanel/TimerEditPanel.tsx
  frontend/src/components/PairRoomOnboarding/CreateBranchModal/CreateBranchModal.styles.ts
  frontend/src/components/PairRoomOnboarding/CreateBranchModal/CreateBranchModal.tsx
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.styles.ts
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.tsx
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.styles.ts
  frontend/src/components/PairRoomOnboarding/PairNameInput/PairNameInput.tsx
  frontend/src/components/PairRoomOnboarding/PairRoleInput/PairRoleInput.styles.ts
  frontend/src/components/PairRoomOnboarding/PairRoleInput/PairRoleInput.tsx
  frontend/src/components/PairRoomOnboarding/ProgressBar/ProgressBar.stories.tsx
  frontend/src/components/PairRoomOnboarding/ProgressBar/ProgressBar.tsx
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.styles.ts
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.tsx
  frontend/src/components/PairRoomOnboarding/RoleSelection/RoleSelection.tsx
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.styles.ts
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.tsx
  frontend/src/components/PairRoomOnboarding/TimerSelection/TimerSelection.tsx
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.tsx
  frontend/src/components/common/Dropdown/HiddenDropdown/HiddenDropdown.tsx
  frontend/src/components/common/Input/Input.styles.ts
  frontend/src/components/common/Input/Input.type.ts
  frontend/src/components/common/Modal/Modal.styles.ts
  frontend/src/constants/PairRoomOnboarding/step.ts
  frontend/src/hooks/Main/usePairNameInputs.test.tsx
  frontend/src/hooks/Main/usePairNameInputs.ts
  frontend/src/hooks/PairRoomOnboarding/useAutoMoveIndex.ts
  frontend/src/hooks/PairRoomOnboarding/usePairRoomInformation.ts
  frontend/src/pages/Main/Main.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.styles.ts
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.type.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/queries/Main/useAddPairRoom.ts
  frontend/src/queries/Main/useAddPairRoomHistory.ts
  frontend/src/queries/Main/useGetPairRoomHistory.ts
  frontend/src/queries/PairRoomOnboarding/useCreateBranch.ts
  frontend/src/queries/PairRoomOnboarding/useGetPairRoomInformation.ts
  frontend/src/utils/PairRoomOnboarding/validate.ts
  frontend/src/validations/common/validatePairName.ts
  frontend/src/validations/validatePairName.ts
  frontend/src/validations/validateTimerDuration.ts
Labels: 🧑‍💻 feat, ⚙️ refactor

#474 [FE] 메인 및 랜딩 페이지 디자인 개선
  frontend/src/components/common/Animation/ScrollAnimationContainer.styles.ts
  frontend/src/components/common/Animation/ScrollAnimationContainer.tsx
  frontend/src/components/common/Background/WaveBackground.styles.ts
  frontend/src/components/common/Background/WaveBackground.tsx
  frontend/src/pages/HowToPair/HowToPair.styles.ts
  frontend/src/pages/Landing/Landing.styles.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/pages/Main/Main.styles.ts
  frontend/src/pages/Main/Main.tsx
Labels: ⚙️ refactor

#475 [FE] 🚀 배포 오류 해결
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoomOnboarding/ProgressBar/ProgressBar.tsx
Labels: 🏗️ infra

#460 [FE] 로그인 시 헤더에 유저 이름이 보이도록 구현
  frontend/src/apis/member.ts
  frontend/src/components/common/Header/Header.styles.ts
  frontend/src/components/common/Header/Header.tsx
  frontend/src/constants/message.ts
Labels: 🧑‍💻 feat

#478 [FE] 페어룸 온보딩 페이지 내 미션과 함께 시작하기 구현
  frontend/src/App.tsx
  frontend/src/components/Main/PairRoomEntryModal/PairRoomEntryModal.tsx
  frontend/src/components/PairRoomOnboarding/CreateBranchModal/CreateBranchModal.styles.ts
  frontend/src/components/PairRoomOnboarding/CreateBranchModal/CreateBranchModal.tsx
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.styles.ts
  frontend/src/components/PairRoomOnboarding/MissionSelectInput/MissionSelectInput.tsx
  frontend/src/components/PairRoomOnboarding/RepositoryButton/RepositoryButton.styles.ts
  frontend/src/components/common/Dropdown/Dropdown/Dropdown.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/queries/Main/useGetPairRoomHistory.ts
  frontend/src/queries/PairRoomOnboarding/useGetRepositories.ts
Labels: 🧑‍💻 feat, ⚙️ refactor

#467 [FE] timer상태 title에 보이도록 구현
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/title/useTitleTime.ts
  frontend/src/pages/Landing/Landing.tsx
  frontend/src/utils/Timer/formatTime.ts
Labels: 🧑‍💻 feat

#487 [FE] 🔖 운영 서버 배포
  frontend/src/apis/todo.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoomOnboarding/TimerDurationInput/TimerDurationInput.tsx
  frontend/src/pages/PairRoomOnboarding/PairRoomOnboarding.tsx
  frontend/src/validations/validateTimerDuration.ts
Labels: 🏗️ infra
