Repository woowacourse-teams/2024-coduo, pull requests merged in 2025-02, with the labels that each got.

#1070 🚀 웹소켓 연결 URL 변경
  frontend/src/apis/websocket/websocket.ts
  frontend/src/hooks/PairRoom/usePairRoom.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/hooks/PairRoom/useTodo.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/stores/socketStore.ts
Labels: 🏗️ infra, 🚑 hotfix

#1071 🚀 투두 생성 URL 변경
  frontend/src/apis/websocket/todo.ts
Labels: 🏗️ infra, 🚑 hotfix

#1075 [FE] 🚀 타이머 시간 변경 오류 해결
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/hooks/PairRoom/useTimer.ts
Labels: 🏗️ infra, 🚑 hotfix

#1085 [FE] 버그 수정
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/stores/toastStore.ts
Labels: 🌋 bug

#1093 [FE] 웹소켓 BE 요구사항 구현
  frontend/src/hooks/PairRoom/useTimer.ts
Labels: 🌋 bug

#1094 [FE] 🚀 레퍼런스 링크와 카테고리 웹소켓 연결 및 버그 수정 사항 테스트 서버 배포
  frontend/src/apis/websocket/reference.ts
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/Footer/Footer.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.stories.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
  frontend/src/hooks/PairRoom/useCategory.ts
  frontend/src/hooks/PairRoom/useEditCategory.ts
  frontend/src/hooks/PairRoom/useReference.ts
  frontend/src/hooks/PairRoom/useTimer.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/useCategoriesMutation.ts
  frontend/src/queries/PairRoom/useReferencesMutation.ts
  frontend/src/queries/PairRoom/useTodosMutation.ts
  frontend/src/stores/toastStore.ts
Labels: 🌋 bug

#1101 [FE] 🚀 타이머 버그 수정 및 잘못된 웹소켓 엔드포인트 수정
  frontend/src/App.tsx
  frontend/src/apis/websocket/reference.ts
  frontend/src/hooks/PairRoom/useTimer.ts
Labels: 🌋 bug

#1107 [FE] 🚀 카테고리 형식을 잘못 지정해주던 오류 수정
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.type.ts
Labels: 🌋 bug

#1109 [FE] 🚀 드롭다운 형식과 카테고리 형식이 맞지 않아 빌드 오류가 발생하던 오류 해결
  frontend/src/apis/websocket/reference.ts
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryManagementModal.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.type.ts
  frontend/src/queries/PairRoom/useCategoriesMutation.ts
Labels: 🌋 bug

#1117 [BE] 페어룸 종료 시 completed STOMP 메세지 전송
  backend/src/main/java/site/coduo/pairroom/domain/PairRoomStatus.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomService.java
  backend/src/main/java/site/coduo/pairroom/service/PairRoomStompManager.java
  backend/src/main/java/site/coduo/pairroom/service/dto/PairRoomStatusResponse.java
Labels: 🧑‍💻 feat

#1119 [FE] 페어룸 종료 상태 STOMP 구현
  frontend/src/hooks/PairRoom/usePairRoomStatusSocket.ts
  frontend/src/hooks/PairRoom/useTimerSocket.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/usePairRoomQuery.ts
Labels: 🧑‍💻 feat

#1120 [FE] 🚀 페어룸 종료 상태 STOMP 구현
  frontend/src/hooks/PairRoom/usePairRoomStatusSocket.ts
  frontend/src/hooks/PairRoom/useReferenceSocket.ts
  frontend/src/hooks/PairRoom/useTimerSocket.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/usePairRoomQuery.ts
Labels: 🏗️ infra

#1121 [FE] 🚀 인자 전달이 되지 않던 오류 해결
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
Labels: 🌋 bug

#1127 [FE] 테스트를 위해 카테고리 필터 로직 제거
  frontend/src/hooks/PairRoom/useReferenceSocket.ts
Labels: 🌋 bug

#1128 [FE] 🚀 카테고리 필터링 로직 삭제 테스트
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/hooks/PairRoom/useReferenceSocket.ts
Labels: 🌋 bug

#1129 [FE] 🚀 카테고리 필터링 로직 추가 테스트
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/hooks/PairRoom/useReferenceSocket.ts
Labels: 🌋 bug

#1131 [FE] 🚀 카테고리 필터링 로직 수정
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
Labels: 🌋 bug

#1132 [FE] 🚀 기본 '전체' 카테고리 추가 테스트
  frontend/src/hooks/PairRoom/useCategorySocket.ts
Labels: 🌋 bug

#1133 [FE] 🚀 전체 카테고리 선택 시 레퍼런스 링크가 등장하지 않는 오류 해결
  frontend/src/components/PairRoom/ReferenceCard/ReferenceList/ReferenceList.tsx
Labels: 🌋 bug

#1096 [FE] Pip 드라이버 이름 추가 및 스타일 수정
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/PairRoom/TimerPip/TimerPip.styles.ts
  frontend/src/components/PairRoom/TimerPip/TimerPip.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
Labels: ⚙️ refactor, 💄 design

#1135 [FE] 🚀 PIP 수정 및 페어룸 오류 해결
  frontend/src/apis/http/timer.ts
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/PairRoom/TimerPip/TimerPip.styles.ts
  frontend/src/components/PairRoom/TimerPip/TimerPip.tsx
  frontend/src/hooks/PairRoom/usePairRoomStatusSocket.ts
  frontend/src/hooks/PairRoom/useTimerSocket.ts
  frontend/src/pages/PairRoom/PairRoom.tsx
Labels: 🏗️ infra

#1142 [FE] 🚀 페어룸 종료 API 변경
  .github/workflows/fe_review_request.yml
  frontend/src/apis/http/pairRoom.ts
  frontend/src/components/PairRoom/PairListCard/PairListCard.tsx
  frontend/src/queries/PairRoom/usePairRoomMutation.ts
Labels: 🏗️ infra

#1146 [FE] 🚀 버그 해결
  .github/workflows/review_submit_notification.yml
  frontend/src/hooks/PairRoom/usePairRoomStatusSocket.ts
  frontend/src/pages/PrivateRoutes.tsx
Labels: 🏗️ infra

#1147 [FE] 🚀 PrivateRoutes 코드 변경
  frontend/src/pages/PrivateRoutes.tsx
Labels: 🏗️ infra

#1153 [FE] 디스코드 알림 yml 수정
  .github/workflows/fe_review_request.yml
Labels: 🌋 bug

#1151 [FE] 🚀 버그 해결
  .github/workflows/fe_review_request.yml
  frontend/src/components/Retrospect/Header/Header.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/pages/RetrospectForm/RetrospectForm.tsx
  frontend/src/pages/RetrospectView/RetrospectView.tsx
  frontend/src/queries/PairRoom/usePairRoomExistsQuery.ts
Labels: 🏗️ infra

#1162 [FE] 코딩해듀오 가이드북 최신화
  frontend/src/components/CoduoDocs/Quote/Quote.styles.ts
  frontend/src/components/CoduoDocs/Steps/Steps.styles.ts
  frontend/src/components/CoduoDocs/Steps/Steps.tsx
  frontend/src/constants/coduoDocs/howToStart.ts
  frontend/src/constants/coduoDocs/index.ts
  frontend/src/constants/coduoDocs/pairProgrammingConcept.ts
  frontend/src/constants/coduoDocs/sidebar.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.styles.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.tsx
Labels: 🏗️ infra

#1163 [FE] 🚀 코딩해듀오 가이드북 최신화
  frontend/src/components/CoduoDocs/Quote/Quote.styles.ts
  frontend/src/components/CoduoDocs/Steps/Steps.styles.ts
  frontend/src/components/CoduoDocs/Steps/Steps.tsx
  frontend/src/components/PairRoom/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/constants/coduoDocs/howToStart.ts
  frontend/src/constants/coduoDocs/index.ts
  frontend/src/constants/coduoDocs/pairProgrammingConcept.ts
  frontend/src/constants/coduoDocs/sidebar.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.styles.ts
  frontend/src/pages/CoduoDocs/CoduoDocs.tsx
Labels: 🏗️ infra

#1174 [FE] 중복 toast 문제 해결
  frontend/src/queries/PairRoom/usePairRoomMutation.ts
  frontend/src/queries/PairRoom/useTimerMutation.ts
Labels: 🌋 bug

#1176 [FE] 🚀 중복 toast 문제 해결 테스트 배포
  frontend/src/queries/PairRoom/usePairRoomMutation.ts
  frontend/src/queries/PairRoom/useTimerMutation.ts
Labels: 🌋 bug

#1178 [FE] 🚀 카테고리 변경 문구 수정
  frontend/src/components/CompletedPairRoom/CategoryManagementModal/CategoryItem/CategoryItem.tsx
Labels: 🌋 bug, 🚑 hotfix

#1179 [FE] 🔖 프론트 버그 수정 사항 production 배포
  frontend/src/components/CompletedPairRoom/CategoryManagementModal/CategoryItem/CategoryItem.tsx
  frontend/src/queries/PairRoom/usePairRoomMutation.ts
  frontend/src/queries/PairRoom/useTimerMutation.ts
Labels: 🌋 bug, 🏗️ infra

#1182 [FE] 🚀 Stomp 재구독 로직 추가
  frontend/src/apis/websocket/websocket.ts
Labels: 🌋 bug

#1184 [FE] 🚀 구독 useEffect 의존성에 isConnected 추가
  frontend/src/hooks/PairRoom/useCategorySocket.ts
  frontend/src/hooks/PairRoom/usePairRoomStatusSocket.ts
  frontend/src/hooks/PairRoom/useReferenceSocket.ts
  frontend/src/hooks/PairRoom/useTimerSocket.ts
  frontend/src/hooks/PairRoom/useTodoSocket.ts
Labels: 🌋 bug

#1186 [FE] 타이머가 진행중입니다 toast 삭제
  frontend/src/hooks/PairRoom/useTimerSocket.ts
Labels: 🌋 bug

#1189 [FE] 🚀 PairRoleCard 색상이 잘못되어있던 문제 해결
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
Labels: 🌋 bug

#1190 [FE] 🚀 PairRoleCard 드라이버 배경 그라디언트 색상 조정
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
Labels: 🌋 bug

#1191 [FE] 🔖 버그 수정 내역 deploy
  frontend/src/apis/websocket/websocket.ts
  frontend/src/components/PairRoom/PairRoleCard/PairRoleCard.styles.ts
  frontend/src/hooks/PairRoom/useCategorySocket.ts
  frontend/src/hooks/PairRoom/usePairRoomStatusSocket.ts
  frontend/src/hooks/PairRoom/useReferenceSocket.ts
  frontend/src/hooks/PairRoom/useTimerSocket.ts
  frontend/src/hooks/PairRoom/useTodoSocket.ts
Labels: 🌋 bug
