Repository woowacourse-teams/2024-coduo, pull requests merged in 2025-01, with the labels that each got.

#1031 [FE] 중복 getTimer api 삭제 및 타이머 웹소켓 연결
  frontend/src/apis/pairRoom.ts
  frontend/src/apis/timer.ts
  frontend/src/queries/PairRoom/usePairRoomQuery.ts
Labels: 🧑‍💻 feat

#1035 [FE] GetPairRoom, getTodos, getReferenceLinks api 통합
  frontend/src/apis/pairRoom.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.stories.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoList/TodoList.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/usePairRoomQuery.ts
Labels: ⚙️ refactor

#1037 [FE] 🚀 getPairRoom api 배포 테스트
  .github/workflows/pull_request.yml
  .github/workflows/review_request.yml
  frontend/src/apis/pairRoom.ts
  frontend/src/apis/timer.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.stories.tsx
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoList/TodoList.tsx
  frontend/src/components/PairRoom/TodoListCard/TodoListCard.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/usePairRoomQuery.ts
Labels: 🏗️ infra, ⚙️ refactor

#1040 [FE] 🚀 카테고리도 getPairRoom api에서 불러오도록 변경
  frontend/src/apis/pairRoom.ts
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.tsx
  frontend/src/pages/PairRoom/PairRoom.tsx
  frontend/src/queries/PairRoom/usePairRoomQuery.ts
Labels: 🌋 bug, 🚑 hotfix

#1042 [FE] 🚀 빌드 오류 해결
  frontend/src/components/PairRoom/ReferenceCard/ReferenceCard.stories.tsx
Labels: 🌋 bug

#1043 [FE] 🚀 웹소켓 프로토콜 wss에서 ws로 복구
  frontend/src/apis/timer.ts
Labels: 🌋 bug

#1057 [FE] Timer Pip 구현
  frontend/src/components/PairRoom/TimerCard/TimerCard.tsx
  frontend/src/components/PairRoom/TimerPip/TimerPip.styles.ts
  frontend/src/components/PairRoom/TimerPip/TimerPip.tsx
Labels: 🧑‍💻 feat, 💄 design
